// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module AXI4AIA(
  input         clock,
  input         reset,
  output        toaia_0_aw_ready,
  input         toaia_0_aw_valid,
  input  [3:0]  toaia_0_aw_bits_id,
  input  [31:0] toaia_0_aw_bits_addr,
  input  [7:0]  toaia_0_aw_bits_len,
  input  [2:0]  toaia_0_aw_bits_size,
  input  [1:0]  toaia_0_aw_bits_burst,
  input         toaia_0_aw_bits_lock,
  input  [3:0]  toaia_0_aw_bits_cache,
  input  [2:0]  toaia_0_aw_bits_prot,
  input  [3:0]  toaia_0_aw_bits_qos,
  output        toaia_0_w_ready,
  input         toaia_0_w_valid,
  input  [31:0] toaia_0_w_bits_data,
  input  [3:0]  toaia_0_w_bits_strb,
  input         toaia_0_w_bits_last,
  input         toaia_0_b_ready,
  output        toaia_0_b_valid,
  output [3:0]  toaia_0_b_bits_id,
  output [1:0]  toaia_0_b_bits_resp,
  output        toaia_0_ar_ready,
  input         toaia_0_ar_valid,
  input  [3:0]  toaia_0_ar_bits_id,
  input  [31:0] toaia_0_ar_bits_addr,
  input  [7:0]  toaia_0_ar_bits_len,
  input  [2:0]  toaia_0_ar_bits_size,
  input  [1:0]  toaia_0_ar_bits_burst,
  input         toaia_0_ar_bits_lock,
  input  [3:0]  toaia_0_ar_bits_cache,
  input  [2:0]  toaia_0_ar_bits_prot,
  input  [3:0]  toaia_0_ar_bits_qos,
  input         toaia_0_r_ready,
  output        toaia_0_r_valid,
  output [3:0]  toaia_0_r_bits_id,
  output [31:0] toaia_0_r_bits_data,
  output [1:0]  toaia_0_r_bits_resp,
  output        toaia_0_r_bits_last,
  output        toCSR0_rdata_valid,
  output [63:0] toCSR0_rdata_bits,
  output        toCSR0_illegal,
  output [5:0]  toCSR0_pendings,
  output [31:0] toCSR0_topeis_0,
  output [31:0] toCSR0_topeis_1,
  output [31:0] toCSR0_topeis_2,
  input         fromCSR0_addr_valid,
  input  [11:0] fromCSR0_addr_bits,
  input         fromCSR0_virt,
  input  [1:0]  fromCSR0_priv,
  input  [5:0]  fromCSR0_vgein,
  input         fromCSR0_wdata_valid,
  input  [1:0]  fromCSR0_wdata_bits_op,
  input  [63:0] fromCSR0_wdata_bits_data,
  input         fromCSR0_claims_0,
  input         fromCSR0_claims_1,
  input         fromCSR0_claims_2,
  output        toCSR1_rdata_valid,
  output [63:0] toCSR1_rdata_bits,
  output        toCSR1_illegal,
  output [5:0]  toCSR1_pendings,
  output [31:0] toCSR1_topeis_0,
  output [31:0] toCSR1_topeis_1,
  output [31:0] toCSR1_topeis_2,
  input         fromCSR1_addr_valid,
  input  [11:0] fromCSR1_addr_bits,
  input         fromCSR1_virt,
  input  [1:0]  fromCSR1_priv,
  input  [5:0]  fromCSR1_vgein,
  input         fromCSR1_wdata_valid,
  input  [1:0]  fromCSR1_wdata_bits_op,
  input  [63:0] fromCSR1_wdata_bits_data,
  input         fromCSR1_claims_0,
  input         fromCSR1_claims_1,
  input         fromCSR1_claims_2,
  output        toCSR2_rdata_valid,
  output [63:0] toCSR2_rdata_bits,
  output        toCSR2_illegal,
  output [5:0]  toCSR2_pendings,
  output [31:0] toCSR2_topeis_0,
  output [31:0] toCSR2_topeis_1,
  output [31:0] toCSR2_topeis_2,
  input         fromCSR2_addr_valid,
  input  [11:0] fromCSR2_addr_bits,
  input         fromCSR2_virt,
  input  [1:0]  fromCSR2_priv,
  input  [5:0]  fromCSR2_vgein,
  input         fromCSR2_wdata_valid,
  input  [1:0]  fromCSR2_wdata_bits_op,
  input  [63:0] fromCSR2_wdata_bits_data,
  input         fromCSR2_claims_0,
  input         fromCSR2_claims_1,
  input         fromCSR2_claims_2,
  output        toCSR3_rdata_valid,
  output [63:0] toCSR3_rdata_bits,
  output        toCSR3_illegal,
  output [5:0]  toCSR3_pendings,
  output [31:0] toCSR3_topeis_0,
  output [31:0] toCSR3_topeis_1,
  output [31:0] toCSR3_topeis_2,
  input         fromCSR3_addr_valid,
  input  [11:0] fromCSR3_addr_bits,
  input         fromCSR3_virt,
  input  [1:0]  fromCSR3_priv,
  input  [5:0]  fromCSR3_vgein,
  input         fromCSR3_wdata_valid,
  input  [1:0]  fromCSR3_wdata_bits_op,
  input  [63:0] fromCSR3_wdata_bits_data,
  input         fromCSR3_claims_0,
  input         fromCSR3_claims_1,
  input         fromCSR3_claims_2,
  input         intSrcs_0,
  input         intSrcs_1,
  input         intSrcs_2,
  input         intSrcs_3,
  input         intSrcs_4,
  input         intSrcs_5,
  input         intSrcs_6,
  input         intSrcs_7,
  input         intSrcs_8,
  input         intSrcs_9,
  input         intSrcs_10,
  input         intSrcs_11,
  input         intSrcs_12,
  input         intSrcs_13,
  input         intSrcs_14,
  input         intSrcs_15,
  input         intSrcs_16,
  input         intSrcs_17,
  input         intSrcs_18,
  input         intSrcs_19,
  input         intSrcs_20,
  input         intSrcs_21,
  input         intSrcs_22,
  input         intSrcs_23,
  input         intSrcs_24,
  input         intSrcs_25,
  input         intSrcs_26,
  input         intSrcs_27,
  input         intSrcs_28,
  input         intSrcs_29,
  input         intSrcs_30,
  input         intSrcs_31,
  input         intSrcs_32,
  input         intSrcs_33,
  input         intSrcs_34,
  input         intSrcs_35,
  input         intSrcs_36,
  input         intSrcs_37,
  input         intSrcs_38,
  input         intSrcs_39,
  input         intSrcs_40,
  input         intSrcs_41,
  input         intSrcs_42,
  input         intSrcs_43,
  input         intSrcs_44,
  input         intSrcs_45,
  input         intSrcs_46,
  input         intSrcs_47,
  input         intSrcs_48,
  input         intSrcs_49,
  input         intSrcs_50,
  input         intSrcs_51,
  input         intSrcs_52,
  input         intSrcs_53,
  input         intSrcs_54,
  input         intSrcs_55,
  input         intSrcs_56,
  input         intSrcs_57,
  input         intSrcs_58,
  input         intSrcs_59,
  input         intSrcs_60,
  input         intSrcs_61,
  input         intSrcs_62,
  input         intSrcs_63,
  input         intSrcs_64,
  input         intSrcs_65,
  input         intSrcs_66,
  input         intSrcs_67,
  input         intSrcs_68,
  input         intSrcs_69,
  input         intSrcs_70,
  input         intSrcs_71,
  input         intSrcs_72,
  input         intSrcs_73,
  input         intSrcs_74,
  input         intSrcs_75,
  input         intSrcs_76,
  input         intSrcs_77,
  input         intSrcs_78,
  input         intSrcs_79,
  input         intSrcs_80,
  input         intSrcs_81,
  input         intSrcs_82,
  input         intSrcs_83,
  input         intSrcs_84,
  input         intSrcs_85,
  input         intSrcs_86,
  input         intSrcs_87,
  input         intSrcs_88,
  input         intSrcs_89,
  input         intSrcs_90,
  input         intSrcs_91,
  input         intSrcs_92,
  input         intSrcs_93,
  input         intSrcs_94,
  input         intSrcs_95,
  input         intSrcs_96,
  input         intSrcs_97,
  input         intSrcs_98,
  input         intSrcs_99,
  input         intSrcs_100,
  input         intSrcs_101,
  input         intSrcs_102,
  input         intSrcs_103,
  input         intSrcs_104,
  input         intSrcs_105,
  input         intSrcs_106,
  input         intSrcs_107,
  input         intSrcs_108,
  input         intSrcs_109,
  input         intSrcs_110,
  input         intSrcs_111,
  input         intSrcs_112,
  input         intSrcs_113,
  input         intSrcs_114,
  input         intSrcs_115,
  input         intSrcs_116,
  input         intSrcs_117,
  input         intSrcs_118,
  input         intSrcs_119,
  input         intSrcs_120,
  input         intSrcs_121,
  input         intSrcs_122,
  input         intSrcs_123,
  input         intSrcs_124,
  input         intSrcs_125,
  input         intSrcs_126,
  input         intSrcs_127
);

  wire        _aplic_auto_toIMSIC_out_aw_valid;
  wire [4:0]  _aplic_auto_toIMSIC_out_aw_bits_id;
  wire [31:0] _aplic_auto_toIMSIC_out_aw_bits_addr;
  wire [2:0]  _aplic_auto_toIMSIC_out_aw_bits_size;
  wire        _aplic_auto_toIMSIC_out_w_valid;
  wire [31:0] _aplic_auto_toIMSIC_out_w_bits_data;
  wire [3:0]  _aplic_auto_toIMSIC_out_w_bits_strb;
  wire        _aplic_auto_toIMSIC_out_w_bits_last;
  wire        _aplic_auto_toIMSIC_out_b_ready;
  wire        _aplic_auto_fromCPU_in_aw_ready;
  wire        _aplic_auto_fromCPU_in_w_ready;
  wire        _aplic_auto_fromCPU_in_b_valid;
  wire [3:0]  _aplic_auto_fromCPU_in_b_bits_id;
  wire [1:0]  _aplic_auto_fromCPU_in_b_bits_resp;
  wire        _aplic_auto_fromCPU_in_ar_ready;
  wire        _aplic_auto_fromCPU_in_r_valid;
  wire [3:0]  _aplic_auto_fromCPU_in_r_bits_id;
  wire [31:0] _aplic_auto_fromCPU_in_r_bits_data;
  wire [1:0]  _aplic_auto_fromCPU_in_r_bits_resp;
  wire        _aplic_auto_fromCPU_in_r_bits_last;
  wire        _imsic_3_auto_axireg_axireg_axi4xbar_in_b_valid;
  wire [5:0]  _imsic_3_auto_axireg_axireg_axi4xbar_in_b_bits_id;
  wire [1:0]  _imsic_3_auto_axireg_axireg_axi4xbar_in_b_bits_resp;
  wire        _imsic_3_auto_axireg_axireg_axi4xbar_in_ar_ready;
  wire        _imsic_3_auto_axireg_axireg_axi4xbar_in_r_valid;
  wire [5:0]  _imsic_3_auto_axireg_axireg_axi4xbar_in_r_bits_id;
  wire [31:0] _imsic_3_auto_axireg_axireg_axi4xbar_in_r_bits_data;
  wire [1:0]  _imsic_3_auto_axireg_axireg_axi4xbar_in_r_bits_resp;
  wire        _imsic_3_auto_axireg_axireg_axi4xbar_in_r_bits_last;
  wire        _axi4map_3_auto_in_b_valid;
  wire [5:0]  _axi4map_3_auto_in_b_bits_id;
  wire [1:0]  _axi4map_3_auto_in_b_bits_resp;
  wire        _axi4map_3_auto_in_ar_ready;
  wire        _axi4map_3_auto_in_r_valid;
  wire [5:0]  _axi4map_3_auto_in_r_bits_id;
  wire [31:0] _axi4map_3_auto_in_r_bits_data;
  wire [1:0]  _axi4map_3_auto_in_r_bits_resp;
  wire        _axi4map_3_auto_in_r_bits_last;
  wire        _axi4map_3_auto_out_aw_valid;
  wire [5:0]  _axi4map_3_auto_out_aw_bits_id;
  wire [16:0] _axi4map_3_auto_out_aw_bits_addr;
  wire [7:0]  _axi4map_3_auto_out_aw_bits_len;
  wire [2:0]  _axi4map_3_auto_out_aw_bits_size;
  wire [1:0]  _axi4map_3_auto_out_aw_bits_burst;
  wire        _axi4map_3_auto_out_aw_bits_lock;
  wire [3:0]  _axi4map_3_auto_out_aw_bits_cache;
  wire [2:0]  _axi4map_3_auto_out_aw_bits_prot;
  wire [3:0]  _axi4map_3_auto_out_aw_bits_qos;
  wire        _axi4map_3_auto_out_w_valid;
  wire [31:0] _axi4map_3_auto_out_w_bits_data;
  wire [3:0]  _axi4map_3_auto_out_w_bits_strb;
  wire        _axi4map_3_auto_out_w_bits_last;
  wire        _axi4map_3_auto_out_b_ready;
  wire        _axi4map_3_auto_out_ar_valid;
  wire [5:0]  _axi4map_3_auto_out_ar_bits_id;
  wire [16:0] _axi4map_3_auto_out_ar_bits_addr;
  wire [7:0]  _axi4map_3_auto_out_ar_bits_len;
  wire [2:0]  _axi4map_3_auto_out_ar_bits_size;
  wire [1:0]  _axi4map_3_auto_out_ar_bits_burst;
  wire        _axi4map_3_auto_out_ar_bits_lock;
  wire [3:0]  _axi4map_3_auto_out_ar_bits_cache;
  wire [2:0]  _axi4map_3_auto_out_ar_bits_prot;
  wire [3:0]  _axi4map_3_auto_out_ar_bits_qos;
  wire        _axi4map_3_auto_out_r_ready;
  wire        _imsic_2_auto_axireg_axireg_axi4xbar_in_b_valid;
  wire [5:0]  _imsic_2_auto_axireg_axireg_axi4xbar_in_b_bits_id;
  wire [1:0]  _imsic_2_auto_axireg_axireg_axi4xbar_in_b_bits_resp;
  wire        _imsic_2_auto_axireg_axireg_axi4xbar_in_ar_ready;
  wire        _imsic_2_auto_axireg_axireg_axi4xbar_in_r_valid;
  wire [5:0]  _imsic_2_auto_axireg_axireg_axi4xbar_in_r_bits_id;
  wire [31:0] _imsic_2_auto_axireg_axireg_axi4xbar_in_r_bits_data;
  wire [1:0]  _imsic_2_auto_axireg_axireg_axi4xbar_in_r_bits_resp;
  wire        _imsic_2_auto_axireg_axireg_axi4xbar_in_r_bits_last;
  wire        _axi4map_2_auto_in_b_valid;
  wire [5:0]  _axi4map_2_auto_in_b_bits_id;
  wire [1:0]  _axi4map_2_auto_in_b_bits_resp;
  wire        _axi4map_2_auto_in_ar_ready;
  wire        _axi4map_2_auto_in_r_valid;
  wire [5:0]  _axi4map_2_auto_in_r_bits_id;
  wire [31:0] _axi4map_2_auto_in_r_bits_data;
  wire [1:0]  _axi4map_2_auto_in_r_bits_resp;
  wire        _axi4map_2_auto_in_r_bits_last;
  wire        _axi4map_2_auto_out_aw_valid;
  wire [5:0]  _axi4map_2_auto_out_aw_bits_id;
  wire [16:0] _axi4map_2_auto_out_aw_bits_addr;
  wire [7:0]  _axi4map_2_auto_out_aw_bits_len;
  wire [2:0]  _axi4map_2_auto_out_aw_bits_size;
  wire [1:0]  _axi4map_2_auto_out_aw_bits_burst;
  wire        _axi4map_2_auto_out_aw_bits_lock;
  wire [3:0]  _axi4map_2_auto_out_aw_bits_cache;
  wire [2:0]  _axi4map_2_auto_out_aw_bits_prot;
  wire [3:0]  _axi4map_2_auto_out_aw_bits_qos;
  wire        _axi4map_2_auto_out_w_valid;
  wire [31:0] _axi4map_2_auto_out_w_bits_data;
  wire [3:0]  _axi4map_2_auto_out_w_bits_strb;
  wire        _axi4map_2_auto_out_w_bits_last;
  wire        _axi4map_2_auto_out_b_ready;
  wire        _axi4map_2_auto_out_ar_valid;
  wire [5:0]  _axi4map_2_auto_out_ar_bits_id;
  wire [16:0] _axi4map_2_auto_out_ar_bits_addr;
  wire [7:0]  _axi4map_2_auto_out_ar_bits_len;
  wire [2:0]  _axi4map_2_auto_out_ar_bits_size;
  wire [1:0]  _axi4map_2_auto_out_ar_bits_burst;
  wire        _axi4map_2_auto_out_ar_bits_lock;
  wire [3:0]  _axi4map_2_auto_out_ar_bits_cache;
  wire [2:0]  _axi4map_2_auto_out_ar_bits_prot;
  wire [3:0]  _axi4map_2_auto_out_ar_bits_qos;
  wire        _axi4map_2_auto_out_r_ready;
  wire        _imsic_1_auto_axireg_axireg_axi4xbar_in_b_valid;
  wire [5:0]  _imsic_1_auto_axireg_axireg_axi4xbar_in_b_bits_id;
  wire [1:0]  _imsic_1_auto_axireg_axireg_axi4xbar_in_b_bits_resp;
  wire        _imsic_1_auto_axireg_axireg_axi4xbar_in_ar_ready;
  wire        _imsic_1_auto_axireg_axireg_axi4xbar_in_r_valid;
  wire [5:0]  _imsic_1_auto_axireg_axireg_axi4xbar_in_r_bits_id;
  wire [31:0] _imsic_1_auto_axireg_axireg_axi4xbar_in_r_bits_data;
  wire [1:0]  _imsic_1_auto_axireg_axireg_axi4xbar_in_r_bits_resp;
  wire        _imsic_1_auto_axireg_axireg_axi4xbar_in_r_bits_last;
  wire        _axi4map_1_auto_in_b_valid;
  wire [5:0]  _axi4map_1_auto_in_b_bits_id;
  wire [1:0]  _axi4map_1_auto_in_b_bits_resp;
  wire        _axi4map_1_auto_in_ar_ready;
  wire        _axi4map_1_auto_in_r_valid;
  wire [5:0]  _axi4map_1_auto_in_r_bits_id;
  wire [31:0] _axi4map_1_auto_in_r_bits_data;
  wire [1:0]  _axi4map_1_auto_in_r_bits_resp;
  wire        _axi4map_1_auto_in_r_bits_last;
  wire        _axi4map_1_auto_out_aw_valid;
  wire [5:0]  _axi4map_1_auto_out_aw_bits_id;
  wire [16:0] _axi4map_1_auto_out_aw_bits_addr;
  wire [7:0]  _axi4map_1_auto_out_aw_bits_len;
  wire [2:0]  _axi4map_1_auto_out_aw_bits_size;
  wire [1:0]  _axi4map_1_auto_out_aw_bits_burst;
  wire        _axi4map_1_auto_out_aw_bits_lock;
  wire [3:0]  _axi4map_1_auto_out_aw_bits_cache;
  wire [2:0]  _axi4map_1_auto_out_aw_bits_prot;
  wire [3:0]  _axi4map_1_auto_out_aw_bits_qos;
  wire        _axi4map_1_auto_out_w_valid;
  wire [31:0] _axi4map_1_auto_out_w_bits_data;
  wire [3:0]  _axi4map_1_auto_out_w_bits_strb;
  wire        _axi4map_1_auto_out_w_bits_last;
  wire        _axi4map_1_auto_out_b_ready;
  wire        _axi4map_1_auto_out_ar_valid;
  wire [5:0]  _axi4map_1_auto_out_ar_bits_id;
  wire [16:0] _axi4map_1_auto_out_ar_bits_addr;
  wire [7:0]  _axi4map_1_auto_out_ar_bits_len;
  wire [2:0]  _axi4map_1_auto_out_ar_bits_size;
  wire [1:0]  _axi4map_1_auto_out_ar_bits_burst;
  wire        _axi4map_1_auto_out_ar_bits_lock;
  wire [3:0]  _axi4map_1_auto_out_ar_bits_cache;
  wire [2:0]  _axi4map_1_auto_out_ar_bits_prot;
  wire [3:0]  _axi4map_1_auto_out_ar_bits_qos;
  wire        _axi4map_1_auto_out_r_ready;
  wire        _imsic_auto_axireg_axireg_axi4xbar_in_b_valid;
  wire [5:0]  _imsic_auto_axireg_axireg_axi4xbar_in_b_bits_id;
  wire [1:0]  _imsic_auto_axireg_axireg_axi4xbar_in_b_bits_resp;
  wire        _imsic_auto_axireg_axireg_axi4xbar_in_ar_ready;
  wire        _imsic_auto_axireg_axireg_axi4xbar_in_r_valid;
  wire [5:0]  _imsic_auto_axireg_axireg_axi4xbar_in_r_bits_id;
  wire [31:0] _imsic_auto_axireg_axireg_axi4xbar_in_r_bits_data;
  wire [1:0]  _imsic_auto_axireg_axireg_axi4xbar_in_r_bits_resp;
  wire        _imsic_auto_axireg_axireg_axi4xbar_in_r_bits_last;
  wire        _axi4map_auto_in_b_valid;
  wire [5:0]  _axi4map_auto_in_b_bits_id;
  wire [1:0]  _axi4map_auto_in_b_bits_resp;
  wire        _axi4map_auto_in_ar_ready;
  wire        _axi4map_auto_in_r_valid;
  wire [5:0]  _axi4map_auto_in_r_bits_id;
  wire [31:0] _axi4map_auto_in_r_bits_data;
  wire [1:0]  _axi4map_auto_in_r_bits_resp;
  wire        _axi4map_auto_in_r_bits_last;
  wire        _axi4map_auto_out_aw_valid;
  wire [5:0]  _axi4map_auto_out_aw_bits_id;
  wire [16:0] _axi4map_auto_out_aw_bits_addr;
  wire [7:0]  _axi4map_auto_out_aw_bits_len;
  wire [2:0]  _axi4map_auto_out_aw_bits_size;
  wire [1:0]  _axi4map_auto_out_aw_bits_burst;
  wire        _axi4map_auto_out_aw_bits_lock;
  wire [3:0]  _axi4map_auto_out_aw_bits_cache;
  wire [2:0]  _axi4map_auto_out_aw_bits_prot;
  wire [3:0]  _axi4map_auto_out_aw_bits_qos;
  wire        _axi4map_auto_out_w_valid;
  wire [31:0] _axi4map_auto_out_w_bits_data;
  wire [3:0]  _axi4map_auto_out_w_bits_strb;
  wire        _axi4map_auto_out_w_bits_last;
  wire        _axi4map_auto_out_b_ready;
  wire        _axi4map_auto_out_ar_valid;
  wire [5:0]  _axi4map_auto_out_ar_bits_id;
  wire [16:0] _axi4map_auto_out_ar_bits_addr;
  wire [7:0]  _axi4map_auto_out_ar_bits_len;
  wire [2:0]  _axi4map_auto_out_ar_bits_size;
  wire [1:0]  _axi4map_auto_out_ar_bits_burst;
  wire        _axi4map_auto_out_ar_bits_lock;
  wire [3:0]  _axi4map_auto_out_ar_bits_cache;
  wire [2:0]  _axi4map_auto_out_ar_bits_prot;
  wire [3:0]  _axi4map_auto_out_ar_bits_qos;
  wire        _axi4map_auto_out_r_ready;
  wire        _imsics_fromMem_xbar_auto_in_1_b_valid;
  wire [4:0]  _imsics_fromMem_xbar_auto_in_1_b_bits_id;
  wire        _imsics_fromMem_xbar_auto_in_1_r_valid;
  wire [4:0]  _imsics_fromMem_xbar_auto_in_1_r_bits_id;
  wire        _imsics_fromMem_xbar_auto_in_0_b_valid;
  wire [3:0]  _imsics_fromMem_xbar_auto_in_0_b_bits_id;
  wire [1:0]  _imsics_fromMem_xbar_auto_in_0_b_bits_resp;
  wire        _imsics_fromMem_xbar_auto_in_0_ar_ready;
  wire        _imsics_fromMem_xbar_auto_in_0_r_valid;
  wire [3:0]  _imsics_fromMem_xbar_auto_in_0_r_bits_id;
  wire [31:0] _imsics_fromMem_xbar_auto_in_0_r_bits_data;
  wire [1:0]  _imsics_fromMem_xbar_auto_in_0_r_bits_resp;
  wire        _imsics_fromMem_xbar_auto_in_0_r_bits_last;
  wire        _imsics_fromMem_xbar_auto_out_3_aw_valid;
  wire [5:0]  _imsics_fromMem_xbar_auto_out_3_aw_bits_id;
  wire [31:0] _imsics_fromMem_xbar_auto_out_3_aw_bits_addr;
  wire [7:0]  _imsics_fromMem_xbar_auto_out_3_aw_bits_len;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_3_aw_bits_size;
  wire [1:0]  _imsics_fromMem_xbar_auto_out_3_aw_bits_burst;
  wire        _imsics_fromMem_xbar_auto_out_3_aw_bits_lock;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_3_aw_bits_cache;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_3_aw_bits_prot;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_3_aw_bits_qos;
  wire        _imsics_fromMem_xbar_auto_out_3_w_valid;
  wire [31:0] _imsics_fromMem_xbar_auto_out_3_w_bits_data;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_3_w_bits_strb;
  wire        _imsics_fromMem_xbar_auto_out_3_w_bits_last;
  wire        _imsics_fromMem_xbar_auto_out_3_b_ready;
  wire        _imsics_fromMem_xbar_auto_out_3_ar_valid;
  wire [5:0]  _imsics_fromMem_xbar_auto_out_3_ar_bits_id;
  wire [31:0] _imsics_fromMem_xbar_auto_out_3_ar_bits_addr;
  wire [7:0]  _imsics_fromMem_xbar_auto_out_3_ar_bits_len;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_3_ar_bits_size;
  wire [1:0]  _imsics_fromMem_xbar_auto_out_3_ar_bits_burst;
  wire        _imsics_fromMem_xbar_auto_out_3_ar_bits_lock;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_3_ar_bits_cache;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_3_ar_bits_prot;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_3_ar_bits_qos;
  wire        _imsics_fromMem_xbar_auto_out_3_r_ready;
  wire        _imsics_fromMem_xbar_auto_out_2_aw_valid;
  wire [5:0]  _imsics_fromMem_xbar_auto_out_2_aw_bits_id;
  wire [31:0] _imsics_fromMem_xbar_auto_out_2_aw_bits_addr;
  wire [7:0]  _imsics_fromMem_xbar_auto_out_2_aw_bits_len;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_2_aw_bits_size;
  wire [1:0]  _imsics_fromMem_xbar_auto_out_2_aw_bits_burst;
  wire        _imsics_fromMem_xbar_auto_out_2_aw_bits_lock;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_2_aw_bits_cache;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_2_aw_bits_prot;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_2_aw_bits_qos;
  wire        _imsics_fromMem_xbar_auto_out_2_w_valid;
  wire [31:0] _imsics_fromMem_xbar_auto_out_2_w_bits_data;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_2_w_bits_strb;
  wire        _imsics_fromMem_xbar_auto_out_2_w_bits_last;
  wire        _imsics_fromMem_xbar_auto_out_2_b_ready;
  wire        _imsics_fromMem_xbar_auto_out_2_ar_valid;
  wire [5:0]  _imsics_fromMem_xbar_auto_out_2_ar_bits_id;
  wire [31:0] _imsics_fromMem_xbar_auto_out_2_ar_bits_addr;
  wire [7:0]  _imsics_fromMem_xbar_auto_out_2_ar_bits_len;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_2_ar_bits_size;
  wire [1:0]  _imsics_fromMem_xbar_auto_out_2_ar_bits_burst;
  wire        _imsics_fromMem_xbar_auto_out_2_ar_bits_lock;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_2_ar_bits_cache;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_2_ar_bits_prot;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_2_ar_bits_qos;
  wire        _imsics_fromMem_xbar_auto_out_2_r_ready;
  wire        _imsics_fromMem_xbar_auto_out_1_aw_valid;
  wire [5:0]  _imsics_fromMem_xbar_auto_out_1_aw_bits_id;
  wire [31:0] _imsics_fromMem_xbar_auto_out_1_aw_bits_addr;
  wire [7:0]  _imsics_fromMem_xbar_auto_out_1_aw_bits_len;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_1_aw_bits_size;
  wire [1:0]  _imsics_fromMem_xbar_auto_out_1_aw_bits_burst;
  wire        _imsics_fromMem_xbar_auto_out_1_aw_bits_lock;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_1_aw_bits_cache;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_1_aw_bits_prot;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_1_aw_bits_qos;
  wire        _imsics_fromMem_xbar_auto_out_1_w_valid;
  wire [31:0] _imsics_fromMem_xbar_auto_out_1_w_bits_data;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_1_w_bits_strb;
  wire        _imsics_fromMem_xbar_auto_out_1_w_bits_last;
  wire        _imsics_fromMem_xbar_auto_out_1_b_ready;
  wire        _imsics_fromMem_xbar_auto_out_1_ar_valid;
  wire [5:0]  _imsics_fromMem_xbar_auto_out_1_ar_bits_id;
  wire [31:0] _imsics_fromMem_xbar_auto_out_1_ar_bits_addr;
  wire [7:0]  _imsics_fromMem_xbar_auto_out_1_ar_bits_len;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_1_ar_bits_size;
  wire [1:0]  _imsics_fromMem_xbar_auto_out_1_ar_bits_burst;
  wire        _imsics_fromMem_xbar_auto_out_1_ar_bits_lock;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_1_ar_bits_cache;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_1_ar_bits_prot;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_1_ar_bits_qos;
  wire        _imsics_fromMem_xbar_auto_out_1_r_ready;
  wire        _imsics_fromMem_xbar_auto_out_0_aw_valid;
  wire [5:0]  _imsics_fromMem_xbar_auto_out_0_aw_bits_id;
  wire [31:0] _imsics_fromMem_xbar_auto_out_0_aw_bits_addr;
  wire [7:0]  _imsics_fromMem_xbar_auto_out_0_aw_bits_len;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_0_aw_bits_size;
  wire [1:0]  _imsics_fromMem_xbar_auto_out_0_aw_bits_burst;
  wire        _imsics_fromMem_xbar_auto_out_0_aw_bits_lock;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_0_aw_bits_cache;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_0_aw_bits_prot;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_0_aw_bits_qos;
  wire        _imsics_fromMem_xbar_auto_out_0_w_valid;
  wire [31:0] _imsics_fromMem_xbar_auto_out_0_w_bits_data;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_0_w_bits_strb;
  wire        _imsics_fromMem_xbar_auto_out_0_w_bits_last;
  wire        _imsics_fromMem_xbar_auto_out_0_b_ready;
  wire        _imsics_fromMem_xbar_auto_out_0_ar_valid;
  wire [5:0]  _imsics_fromMem_xbar_auto_out_0_ar_bits_id;
  wire [31:0] _imsics_fromMem_xbar_auto_out_0_ar_bits_addr;
  wire [7:0]  _imsics_fromMem_xbar_auto_out_0_ar_bits_len;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_0_ar_bits_size;
  wire [1:0]  _imsics_fromMem_xbar_auto_out_0_ar_bits_burst;
  wire        _imsics_fromMem_xbar_auto_out_0_ar_bits_lock;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_0_ar_bits_cache;
  wire [2:0]  _imsics_fromMem_xbar_auto_out_0_ar_bits_prot;
  wire [3:0]  _imsics_fromMem_xbar_auto_out_0_ar_bits_qos;
  wire        _imsics_fromMem_xbar_auto_out_0_r_ready;
  wire        _toAIA_xbar_auto_out_1_aw_valid;
  wire [3:0]  _toAIA_xbar_auto_out_1_aw_bits_id;
  wire [28:0] _toAIA_xbar_auto_out_1_aw_bits_addr;
  wire [7:0]  _toAIA_xbar_auto_out_1_aw_bits_len;
  wire [2:0]  _toAIA_xbar_auto_out_1_aw_bits_size;
  wire [1:0]  _toAIA_xbar_auto_out_1_aw_bits_burst;
  wire        _toAIA_xbar_auto_out_1_aw_bits_lock;
  wire [3:0]  _toAIA_xbar_auto_out_1_aw_bits_cache;
  wire [2:0]  _toAIA_xbar_auto_out_1_aw_bits_prot;
  wire [3:0]  _toAIA_xbar_auto_out_1_aw_bits_qos;
  wire        _toAIA_xbar_auto_out_1_w_valid;
  wire [31:0] _toAIA_xbar_auto_out_1_w_bits_data;
  wire [3:0]  _toAIA_xbar_auto_out_1_w_bits_strb;
  wire        _toAIA_xbar_auto_out_1_w_bits_last;
  wire        _toAIA_xbar_auto_out_1_b_ready;
  wire        _toAIA_xbar_auto_out_1_ar_valid;
  wire [3:0]  _toAIA_xbar_auto_out_1_ar_bits_id;
  wire [28:0] _toAIA_xbar_auto_out_1_ar_bits_addr;
  wire [7:0]  _toAIA_xbar_auto_out_1_ar_bits_len;
  wire [2:0]  _toAIA_xbar_auto_out_1_ar_bits_size;
  wire [1:0]  _toAIA_xbar_auto_out_1_ar_bits_burst;
  wire        _toAIA_xbar_auto_out_1_ar_bits_lock;
  wire [3:0]  _toAIA_xbar_auto_out_1_ar_bits_cache;
  wire [2:0]  _toAIA_xbar_auto_out_1_ar_bits_prot;
  wire [3:0]  _toAIA_xbar_auto_out_1_ar_bits_qos;
  wire        _toAIA_xbar_auto_out_1_r_ready;
  wire        _toAIA_xbar_auto_out_0_aw_valid;
  wire [3:0]  _toAIA_xbar_auto_out_0_aw_bits_id;
  wire [31:0] _toAIA_xbar_auto_out_0_aw_bits_addr;
  wire [7:0]  _toAIA_xbar_auto_out_0_aw_bits_len;
  wire [2:0]  _toAIA_xbar_auto_out_0_aw_bits_size;
  wire [1:0]  _toAIA_xbar_auto_out_0_aw_bits_burst;
  wire        _toAIA_xbar_auto_out_0_aw_bits_lock;
  wire [3:0]  _toAIA_xbar_auto_out_0_aw_bits_cache;
  wire [2:0]  _toAIA_xbar_auto_out_0_aw_bits_prot;
  wire [3:0]  _toAIA_xbar_auto_out_0_aw_bits_qos;
  wire        _toAIA_xbar_auto_out_0_w_valid;
  wire [31:0] _toAIA_xbar_auto_out_0_w_bits_data;
  wire [3:0]  _toAIA_xbar_auto_out_0_w_bits_strb;
  wire        _toAIA_xbar_auto_out_0_w_bits_last;
  wire        _toAIA_xbar_auto_out_0_b_ready;
  wire        _toAIA_xbar_auto_out_0_ar_valid;
  wire [3:0]  _toAIA_xbar_auto_out_0_ar_bits_id;
  wire [31:0] _toAIA_xbar_auto_out_0_ar_bits_addr;
  wire [7:0]  _toAIA_xbar_auto_out_0_ar_bits_len;
  wire [2:0]  _toAIA_xbar_auto_out_0_ar_bits_size;
  wire [1:0]  _toAIA_xbar_auto_out_0_ar_bits_burst;
  wire        _toAIA_xbar_auto_out_0_ar_bits_lock;
  wire [3:0]  _toAIA_xbar_auto_out_0_ar_bits_cache;
  wire [2:0]  _toAIA_xbar_auto_out_0_ar_bits_prot;
  wire [3:0]  _toAIA_xbar_auto_out_0_ar_bits_qos;
  wire        _toAIA_xbar_auto_out_0_r_ready;
  AXI4Xbar toAIA_xbar (
    .clock                    (clock),
    .reset                    (reset),
    .auto_in_aw_ready         (toaia_0_aw_ready),
    .auto_in_aw_valid         (toaia_0_aw_valid),
    .auto_in_aw_bits_id       (toaia_0_aw_bits_id),
    .auto_in_aw_bits_addr     (toaia_0_aw_bits_addr),
    .auto_in_aw_bits_len      (toaia_0_aw_bits_len),
    .auto_in_aw_bits_size     (toaia_0_aw_bits_size),
    .auto_in_aw_bits_burst    (toaia_0_aw_bits_burst),
    .auto_in_aw_bits_lock     (toaia_0_aw_bits_lock),
    .auto_in_aw_bits_cache    (toaia_0_aw_bits_cache),
    .auto_in_aw_bits_prot     (toaia_0_aw_bits_prot),
    .auto_in_aw_bits_qos      (toaia_0_aw_bits_qos),
    .auto_in_w_ready          (toaia_0_w_ready),
    .auto_in_w_valid          (toaia_0_w_valid),
    .auto_in_w_bits_data      (toaia_0_w_bits_data),
    .auto_in_w_bits_strb      (toaia_0_w_bits_strb),
    .auto_in_w_bits_last      (toaia_0_w_bits_last),
    .auto_in_b_ready          (toaia_0_b_ready),
    .auto_in_b_valid          (toaia_0_b_valid),
    .auto_in_b_bits_id        (toaia_0_b_bits_id),
    .auto_in_b_bits_resp      (toaia_0_b_bits_resp),
    .auto_in_ar_ready         (toaia_0_ar_ready),
    .auto_in_ar_valid         (toaia_0_ar_valid),
    .auto_in_ar_bits_id       (toaia_0_ar_bits_id),
    .auto_in_ar_bits_addr     (toaia_0_ar_bits_addr),
    .auto_in_ar_bits_len      (toaia_0_ar_bits_len),
    .auto_in_ar_bits_size     (toaia_0_ar_bits_size),
    .auto_in_ar_bits_burst    (toaia_0_ar_bits_burst),
    .auto_in_ar_bits_lock     (toaia_0_ar_bits_lock),
    .auto_in_ar_bits_cache    (toaia_0_ar_bits_cache),
    .auto_in_ar_bits_prot     (toaia_0_ar_bits_prot),
    .auto_in_ar_bits_qos      (toaia_0_ar_bits_qos),
    .auto_in_r_ready          (toaia_0_r_ready),
    .auto_in_r_valid          (toaia_0_r_valid),
    .auto_in_r_bits_id        (toaia_0_r_bits_id),
    .auto_in_r_bits_data      (toaia_0_r_bits_data),
    .auto_in_r_bits_resp      (toaia_0_r_bits_resp),
    .auto_in_r_bits_last      (toaia_0_r_bits_last),
    .auto_out_1_aw_ready      (_aplic_auto_fromCPU_in_aw_ready),
    .auto_out_1_aw_valid      (_toAIA_xbar_auto_out_1_aw_valid),
    .auto_out_1_aw_bits_id    (_toAIA_xbar_auto_out_1_aw_bits_id),
    .auto_out_1_aw_bits_addr  (_toAIA_xbar_auto_out_1_aw_bits_addr),
    .auto_out_1_aw_bits_len   (_toAIA_xbar_auto_out_1_aw_bits_len),
    .auto_out_1_aw_bits_size  (_toAIA_xbar_auto_out_1_aw_bits_size),
    .auto_out_1_aw_bits_burst (_toAIA_xbar_auto_out_1_aw_bits_burst),
    .auto_out_1_aw_bits_lock  (_toAIA_xbar_auto_out_1_aw_bits_lock),
    .auto_out_1_aw_bits_cache (_toAIA_xbar_auto_out_1_aw_bits_cache),
    .auto_out_1_aw_bits_prot  (_toAIA_xbar_auto_out_1_aw_bits_prot),
    .auto_out_1_aw_bits_qos   (_toAIA_xbar_auto_out_1_aw_bits_qos),
    .auto_out_1_w_ready       (_aplic_auto_fromCPU_in_w_ready),
    .auto_out_1_w_valid       (_toAIA_xbar_auto_out_1_w_valid),
    .auto_out_1_w_bits_data   (_toAIA_xbar_auto_out_1_w_bits_data),
    .auto_out_1_w_bits_strb   (_toAIA_xbar_auto_out_1_w_bits_strb),
    .auto_out_1_w_bits_last   (_toAIA_xbar_auto_out_1_w_bits_last),
    .auto_out_1_b_ready       (_toAIA_xbar_auto_out_1_b_ready),
    .auto_out_1_b_valid       (_aplic_auto_fromCPU_in_b_valid),
    .auto_out_1_b_bits_id     (_aplic_auto_fromCPU_in_b_bits_id),
    .auto_out_1_b_bits_resp   (_aplic_auto_fromCPU_in_b_bits_resp),
    .auto_out_1_ar_ready      (_aplic_auto_fromCPU_in_ar_ready),
    .auto_out_1_ar_valid      (_toAIA_xbar_auto_out_1_ar_valid),
    .auto_out_1_ar_bits_id    (_toAIA_xbar_auto_out_1_ar_bits_id),
    .auto_out_1_ar_bits_addr  (_toAIA_xbar_auto_out_1_ar_bits_addr),
    .auto_out_1_ar_bits_len   (_toAIA_xbar_auto_out_1_ar_bits_len),
    .auto_out_1_ar_bits_size  (_toAIA_xbar_auto_out_1_ar_bits_size),
    .auto_out_1_ar_bits_burst (_toAIA_xbar_auto_out_1_ar_bits_burst),
    .auto_out_1_ar_bits_lock  (_toAIA_xbar_auto_out_1_ar_bits_lock),
    .auto_out_1_ar_bits_cache (_toAIA_xbar_auto_out_1_ar_bits_cache),
    .auto_out_1_ar_bits_prot  (_toAIA_xbar_auto_out_1_ar_bits_prot),
    .auto_out_1_ar_bits_qos   (_toAIA_xbar_auto_out_1_ar_bits_qos),
    .auto_out_1_r_ready       (_toAIA_xbar_auto_out_1_r_ready),
    .auto_out_1_r_valid       (_aplic_auto_fromCPU_in_r_valid),
    .auto_out_1_r_bits_id     (_aplic_auto_fromCPU_in_r_bits_id),
    .auto_out_1_r_bits_data   (_aplic_auto_fromCPU_in_r_bits_data),
    .auto_out_1_r_bits_resp   (_aplic_auto_fromCPU_in_r_bits_resp),
    .auto_out_1_r_bits_last   (_aplic_auto_fromCPU_in_r_bits_last),
    .auto_out_0_aw_valid      (_toAIA_xbar_auto_out_0_aw_valid),
    .auto_out_0_aw_bits_id    (_toAIA_xbar_auto_out_0_aw_bits_id),
    .auto_out_0_aw_bits_addr  (_toAIA_xbar_auto_out_0_aw_bits_addr),
    .auto_out_0_aw_bits_len   (_toAIA_xbar_auto_out_0_aw_bits_len),
    .auto_out_0_aw_bits_size  (_toAIA_xbar_auto_out_0_aw_bits_size),
    .auto_out_0_aw_bits_burst (_toAIA_xbar_auto_out_0_aw_bits_burst),
    .auto_out_0_aw_bits_lock  (_toAIA_xbar_auto_out_0_aw_bits_lock),
    .auto_out_0_aw_bits_cache (_toAIA_xbar_auto_out_0_aw_bits_cache),
    .auto_out_0_aw_bits_prot  (_toAIA_xbar_auto_out_0_aw_bits_prot),
    .auto_out_0_aw_bits_qos   (_toAIA_xbar_auto_out_0_aw_bits_qos),
    .auto_out_0_w_valid       (_toAIA_xbar_auto_out_0_w_valid),
    .auto_out_0_w_bits_data   (_toAIA_xbar_auto_out_0_w_bits_data),
    .auto_out_0_w_bits_strb   (_toAIA_xbar_auto_out_0_w_bits_strb),
    .auto_out_0_w_bits_last   (_toAIA_xbar_auto_out_0_w_bits_last),
    .auto_out_0_b_ready       (_toAIA_xbar_auto_out_0_b_ready),
    .auto_out_0_b_valid       (_imsics_fromMem_xbar_auto_in_0_b_valid),
    .auto_out_0_b_bits_id     (_imsics_fromMem_xbar_auto_in_0_b_bits_id),
    .auto_out_0_b_bits_resp   (_imsics_fromMem_xbar_auto_in_0_b_bits_resp),
    .auto_out_0_ar_ready      (_imsics_fromMem_xbar_auto_in_0_ar_ready),
    .auto_out_0_ar_valid      (_toAIA_xbar_auto_out_0_ar_valid),
    .auto_out_0_ar_bits_id    (_toAIA_xbar_auto_out_0_ar_bits_id),
    .auto_out_0_ar_bits_addr  (_toAIA_xbar_auto_out_0_ar_bits_addr),
    .auto_out_0_ar_bits_len   (_toAIA_xbar_auto_out_0_ar_bits_len),
    .auto_out_0_ar_bits_size  (_toAIA_xbar_auto_out_0_ar_bits_size),
    .auto_out_0_ar_bits_burst (_toAIA_xbar_auto_out_0_ar_bits_burst),
    .auto_out_0_ar_bits_lock  (_toAIA_xbar_auto_out_0_ar_bits_lock),
    .auto_out_0_ar_bits_cache (_toAIA_xbar_auto_out_0_ar_bits_cache),
    .auto_out_0_ar_bits_prot  (_toAIA_xbar_auto_out_0_ar_bits_prot),
    .auto_out_0_ar_bits_qos   (_toAIA_xbar_auto_out_0_ar_bits_qos),
    .auto_out_0_r_ready       (_toAIA_xbar_auto_out_0_r_ready),
    .auto_out_0_r_valid       (_imsics_fromMem_xbar_auto_in_0_r_valid),
    .auto_out_0_r_bits_id     (_imsics_fromMem_xbar_auto_in_0_r_bits_id),
    .auto_out_0_r_bits_data   (_imsics_fromMem_xbar_auto_in_0_r_bits_data),
    .auto_out_0_r_bits_resp   (_imsics_fromMem_xbar_auto_in_0_r_bits_resp),
    .auto_out_0_r_bits_last   (_imsics_fromMem_xbar_auto_in_0_r_bits_last)
  );
  AXI4Xbar_1 imsics_fromMem_xbar (
    .clock                    (clock),
    .reset                    (reset),
    .auto_in_1_aw_valid       (_aplic_auto_toIMSIC_out_aw_valid),
    .auto_in_1_aw_bits_id     (_aplic_auto_toIMSIC_out_aw_bits_id),
    .auto_in_1_aw_bits_addr   (_aplic_auto_toIMSIC_out_aw_bits_addr),
    .auto_in_1_aw_bits_size   (_aplic_auto_toIMSIC_out_aw_bits_size),
    .auto_in_1_w_valid        (_aplic_auto_toIMSIC_out_w_valid),
    .auto_in_1_w_bits_data    (_aplic_auto_toIMSIC_out_w_bits_data),
    .auto_in_1_w_bits_strb    (_aplic_auto_toIMSIC_out_w_bits_strb),
    .auto_in_1_w_bits_last    (_aplic_auto_toIMSIC_out_w_bits_last),
    .auto_in_1_b_ready        (_aplic_auto_toIMSIC_out_b_ready),
    .auto_in_1_b_valid        (_imsics_fromMem_xbar_auto_in_1_b_valid),
    .auto_in_1_b_bits_id      (_imsics_fromMem_xbar_auto_in_1_b_bits_id),
    .auto_in_1_r_valid        (_imsics_fromMem_xbar_auto_in_1_r_valid),
    .auto_in_1_r_bits_id      (_imsics_fromMem_xbar_auto_in_1_r_bits_id),
    .auto_in_0_aw_valid       (_toAIA_xbar_auto_out_0_aw_valid),
    .auto_in_0_aw_bits_id     (_toAIA_xbar_auto_out_0_aw_bits_id),
    .auto_in_0_aw_bits_addr   (_toAIA_xbar_auto_out_0_aw_bits_addr),
    .auto_in_0_aw_bits_len    (_toAIA_xbar_auto_out_0_aw_bits_len),
    .auto_in_0_aw_bits_size   (_toAIA_xbar_auto_out_0_aw_bits_size),
    .auto_in_0_aw_bits_burst  (_toAIA_xbar_auto_out_0_aw_bits_burst),
    .auto_in_0_aw_bits_lock   (_toAIA_xbar_auto_out_0_aw_bits_lock),
    .auto_in_0_aw_bits_cache  (_toAIA_xbar_auto_out_0_aw_bits_cache),
    .auto_in_0_aw_bits_prot   (_toAIA_xbar_auto_out_0_aw_bits_prot),
    .auto_in_0_aw_bits_qos    (_toAIA_xbar_auto_out_0_aw_bits_qos),
    .auto_in_0_w_valid        (_toAIA_xbar_auto_out_0_w_valid),
    .auto_in_0_w_bits_data    (_toAIA_xbar_auto_out_0_w_bits_data),
    .auto_in_0_w_bits_strb    (_toAIA_xbar_auto_out_0_w_bits_strb),
    .auto_in_0_w_bits_last    (_toAIA_xbar_auto_out_0_w_bits_last),
    .auto_in_0_b_ready        (_toAIA_xbar_auto_out_0_b_ready),
    .auto_in_0_b_valid        (_imsics_fromMem_xbar_auto_in_0_b_valid),
    .auto_in_0_b_bits_id      (_imsics_fromMem_xbar_auto_in_0_b_bits_id),
    .auto_in_0_b_bits_resp    (_imsics_fromMem_xbar_auto_in_0_b_bits_resp),
    .auto_in_0_ar_ready       (_imsics_fromMem_xbar_auto_in_0_ar_ready),
    .auto_in_0_ar_valid       (_toAIA_xbar_auto_out_0_ar_valid),
    .auto_in_0_ar_bits_id     (_toAIA_xbar_auto_out_0_ar_bits_id),
    .auto_in_0_ar_bits_addr   (_toAIA_xbar_auto_out_0_ar_bits_addr),
    .auto_in_0_ar_bits_len    (_toAIA_xbar_auto_out_0_ar_bits_len),
    .auto_in_0_ar_bits_size   (_toAIA_xbar_auto_out_0_ar_bits_size),
    .auto_in_0_ar_bits_burst  (_toAIA_xbar_auto_out_0_ar_bits_burst),
    .auto_in_0_ar_bits_lock   (_toAIA_xbar_auto_out_0_ar_bits_lock),
    .auto_in_0_ar_bits_cache  (_toAIA_xbar_auto_out_0_ar_bits_cache),
    .auto_in_0_ar_bits_prot   (_toAIA_xbar_auto_out_0_ar_bits_prot),
    .auto_in_0_ar_bits_qos    (_toAIA_xbar_auto_out_0_ar_bits_qos),
    .auto_in_0_r_ready        (_toAIA_xbar_auto_out_0_r_ready),
    .auto_in_0_r_valid        (_imsics_fromMem_xbar_auto_in_0_r_valid),
    .auto_in_0_r_bits_id      (_imsics_fromMem_xbar_auto_in_0_r_bits_id),
    .auto_in_0_r_bits_data    (_imsics_fromMem_xbar_auto_in_0_r_bits_data),
    .auto_in_0_r_bits_resp    (_imsics_fromMem_xbar_auto_in_0_r_bits_resp),
    .auto_in_0_r_bits_last    (_imsics_fromMem_xbar_auto_in_0_r_bits_last),
    .auto_out_3_aw_valid      (_imsics_fromMem_xbar_auto_out_3_aw_valid),
    .auto_out_3_aw_bits_id    (_imsics_fromMem_xbar_auto_out_3_aw_bits_id),
    .auto_out_3_aw_bits_addr  (_imsics_fromMem_xbar_auto_out_3_aw_bits_addr),
    .auto_out_3_aw_bits_len   (_imsics_fromMem_xbar_auto_out_3_aw_bits_len),
    .auto_out_3_aw_bits_size  (_imsics_fromMem_xbar_auto_out_3_aw_bits_size),
    .auto_out_3_aw_bits_burst (_imsics_fromMem_xbar_auto_out_3_aw_bits_burst),
    .auto_out_3_aw_bits_lock  (_imsics_fromMem_xbar_auto_out_3_aw_bits_lock),
    .auto_out_3_aw_bits_cache (_imsics_fromMem_xbar_auto_out_3_aw_bits_cache),
    .auto_out_3_aw_bits_prot  (_imsics_fromMem_xbar_auto_out_3_aw_bits_prot),
    .auto_out_3_aw_bits_qos   (_imsics_fromMem_xbar_auto_out_3_aw_bits_qos),
    .auto_out_3_w_valid       (_imsics_fromMem_xbar_auto_out_3_w_valid),
    .auto_out_3_w_bits_data   (_imsics_fromMem_xbar_auto_out_3_w_bits_data),
    .auto_out_3_w_bits_strb   (_imsics_fromMem_xbar_auto_out_3_w_bits_strb),
    .auto_out_3_w_bits_last   (_imsics_fromMem_xbar_auto_out_3_w_bits_last),
    .auto_out_3_b_ready       (_imsics_fromMem_xbar_auto_out_3_b_ready),
    .auto_out_3_b_valid       (_axi4map_3_auto_in_b_valid),
    .auto_out_3_b_bits_id     (_axi4map_3_auto_in_b_bits_id),
    .auto_out_3_b_bits_resp   (_axi4map_3_auto_in_b_bits_resp),
    .auto_out_3_ar_ready      (_axi4map_3_auto_in_ar_ready),
    .auto_out_3_ar_valid      (_imsics_fromMem_xbar_auto_out_3_ar_valid),
    .auto_out_3_ar_bits_id    (_imsics_fromMem_xbar_auto_out_3_ar_bits_id),
    .auto_out_3_ar_bits_addr  (_imsics_fromMem_xbar_auto_out_3_ar_bits_addr),
    .auto_out_3_ar_bits_len   (_imsics_fromMem_xbar_auto_out_3_ar_bits_len),
    .auto_out_3_ar_bits_size  (_imsics_fromMem_xbar_auto_out_3_ar_bits_size),
    .auto_out_3_ar_bits_burst (_imsics_fromMem_xbar_auto_out_3_ar_bits_burst),
    .auto_out_3_ar_bits_lock  (_imsics_fromMem_xbar_auto_out_3_ar_bits_lock),
    .auto_out_3_ar_bits_cache (_imsics_fromMem_xbar_auto_out_3_ar_bits_cache),
    .auto_out_3_ar_bits_prot  (_imsics_fromMem_xbar_auto_out_3_ar_bits_prot),
    .auto_out_3_ar_bits_qos   (_imsics_fromMem_xbar_auto_out_3_ar_bits_qos),
    .auto_out_3_r_ready       (_imsics_fromMem_xbar_auto_out_3_r_ready),
    .auto_out_3_r_valid       (_axi4map_3_auto_in_r_valid),
    .auto_out_3_r_bits_id     (_axi4map_3_auto_in_r_bits_id),
    .auto_out_3_r_bits_data   (_axi4map_3_auto_in_r_bits_data),
    .auto_out_3_r_bits_resp   (_axi4map_3_auto_in_r_bits_resp),
    .auto_out_3_r_bits_last   (_axi4map_3_auto_in_r_bits_last),
    .auto_out_2_aw_valid      (_imsics_fromMem_xbar_auto_out_2_aw_valid),
    .auto_out_2_aw_bits_id    (_imsics_fromMem_xbar_auto_out_2_aw_bits_id),
    .auto_out_2_aw_bits_addr  (_imsics_fromMem_xbar_auto_out_2_aw_bits_addr),
    .auto_out_2_aw_bits_len   (_imsics_fromMem_xbar_auto_out_2_aw_bits_len),
    .auto_out_2_aw_bits_size  (_imsics_fromMem_xbar_auto_out_2_aw_bits_size),
    .auto_out_2_aw_bits_burst (_imsics_fromMem_xbar_auto_out_2_aw_bits_burst),
    .auto_out_2_aw_bits_lock  (_imsics_fromMem_xbar_auto_out_2_aw_bits_lock),
    .auto_out_2_aw_bits_cache (_imsics_fromMem_xbar_auto_out_2_aw_bits_cache),
    .auto_out_2_aw_bits_prot  (_imsics_fromMem_xbar_auto_out_2_aw_bits_prot),
    .auto_out_2_aw_bits_qos   (_imsics_fromMem_xbar_auto_out_2_aw_bits_qos),
    .auto_out_2_w_valid       (_imsics_fromMem_xbar_auto_out_2_w_valid),
    .auto_out_2_w_bits_data   (_imsics_fromMem_xbar_auto_out_2_w_bits_data),
    .auto_out_2_w_bits_strb   (_imsics_fromMem_xbar_auto_out_2_w_bits_strb),
    .auto_out_2_w_bits_last   (_imsics_fromMem_xbar_auto_out_2_w_bits_last),
    .auto_out_2_b_ready       (_imsics_fromMem_xbar_auto_out_2_b_ready),
    .auto_out_2_b_valid       (_axi4map_2_auto_in_b_valid),
    .auto_out_2_b_bits_id     (_axi4map_2_auto_in_b_bits_id),
    .auto_out_2_b_bits_resp   (_axi4map_2_auto_in_b_bits_resp),
    .auto_out_2_ar_ready      (_axi4map_2_auto_in_ar_ready),
    .auto_out_2_ar_valid      (_imsics_fromMem_xbar_auto_out_2_ar_valid),
    .auto_out_2_ar_bits_id    (_imsics_fromMem_xbar_auto_out_2_ar_bits_id),
    .auto_out_2_ar_bits_addr  (_imsics_fromMem_xbar_auto_out_2_ar_bits_addr),
    .auto_out_2_ar_bits_len   (_imsics_fromMem_xbar_auto_out_2_ar_bits_len),
    .auto_out_2_ar_bits_size  (_imsics_fromMem_xbar_auto_out_2_ar_bits_size),
    .auto_out_2_ar_bits_burst (_imsics_fromMem_xbar_auto_out_2_ar_bits_burst),
    .auto_out_2_ar_bits_lock  (_imsics_fromMem_xbar_auto_out_2_ar_bits_lock),
    .auto_out_2_ar_bits_cache (_imsics_fromMem_xbar_auto_out_2_ar_bits_cache),
    .auto_out_2_ar_bits_prot  (_imsics_fromMem_xbar_auto_out_2_ar_bits_prot),
    .auto_out_2_ar_bits_qos   (_imsics_fromMem_xbar_auto_out_2_ar_bits_qos),
    .auto_out_2_r_ready       (_imsics_fromMem_xbar_auto_out_2_r_ready),
    .auto_out_2_r_valid       (_axi4map_2_auto_in_r_valid),
    .auto_out_2_r_bits_id     (_axi4map_2_auto_in_r_bits_id),
    .auto_out_2_r_bits_data   (_axi4map_2_auto_in_r_bits_data),
    .auto_out_2_r_bits_resp   (_axi4map_2_auto_in_r_bits_resp),
    .auto_out_2_r_bits_last   (_axi4map_2_auto_in_r_bits_last),
    .auto_out_1_aw_valid      (_imsics_fromMem_xbar_auto_out_1_aw_valid),
    .auto_out_1_aw_bits_id    (_imsics_fromMem_xbar_auto_out_1_aw_bits_id),
    .auto_out_1_aw_bits_addr  (_imsics_fromMem_xbar_auto_out_1_aw_bits_addr),
    .auto_out_1_aw_bits_len   (_imsics_fromMem_xbar_auto_out_1_aw_bits_len),
    .auto_out_1_aw_bits_size  (_imsics_fromMem_xbar_auto_out_1_aw_bits_size),
    .auto_out_1_aw_bits_burst (_imsics_fromMem_xbar_auto_out_1_aw_bits_burst),
    .auto_out_1_aw_bits_lock  (_imsics_fromMem_xbar_auto_out_1_aw_bits_lock),
    .auto_out_1_aw_bits_cache (_imsics_fromMem_xbar_auto_out_1_aw_bits_cache),
    .auto_out_1_aw_bits_prot  (_imsics_fromMem_xbar_auto_out_1_aw_bits_prot),
    .auto_out_1_aw_bits_qos   (_imsics_fromMem_xbar_auto_out_1_aw_bits_qos),
    .auto_out_1_w_valid       (_imsics_fromMem_xbar_auto_out_1_w_valid),
    .auto_out_1_w_bits_data   (_imsics_fromMem_xbar_auto_out_1_w_bits_data),
    .auto_out_1_w_bits_strb   (_imsics_fromMem_xbar_auto_out_1_w_bits_strb),
    .auto_out_1_w_bits_last   (_imsics_fromMem_xbar_auto_out_1_w_bits_last),
    .auto_out_1_b_ready       (_imsics_fromMem_xbar_auto_out_1_b_ready),
    .auto_out_1_b_valid       (_axi4map_1_auto_in_b_valid),
    .auto_out_1_b_bits_id     (_axi4map_1_auto_in_b_bits_id),
    .auto_out_1_b_bits_resp   (_axi4map_1_auto_in_b_bits_resp),
    .auto_out_1_ar_ready      (_axi4map_1_auto_in_ar_ready),
    .auto_out_1_ar_valid      (_imsics_fromMem_xbar_auto_out_1_ar_valid),
    .auto_out_1_ar_bits_id    (_imsics_fromMem_xbar_auto_out_1_ar_bits_id),
    .auto_out_1_ar_bits_addr  (_imsics_fromMem_xbar_auto_out_1_ar_bits_addr),
    .auto_out_1_ar_bits_len   (_imsics_fromMem_xbar_auto_out_1_ar_bits_len),
    .auto_out_1_ar_bits_size  (_imsics_fromMem_xbar_auto_out_1_ar_bits_size),
    .auto_out_1_ar_bits_burst (_imsics_fromMem_xbar_auto_out_1_ar_bits_burst),
    .auto_out_1_ar_bits_lock  (_imsics_fromMem_xbar_auto_out_1_ar_bits_lock),
    .auto_out_1_ar_bits_cache (_imsics_fromMem_xbar_auto_out_1_ar_bits_cache),
    .auto_out_1_ar_bits_prot  (_imsics_fromMem_xbar_auto_out_1_ar_bits_prot),
    .auto_out_1_ar_bits_qos   (_imsics_fromMem_xbar_auto_out_1_ar_bits_qos),
    .auto_out_1_r_ready       (_imsics_fromMem_xbar_auto_out_1_r_ready),
    .auto_out_1_r_valid       (_axi4map_1_auto_in_r_valid),
    .auto_out_1_r_bits_id     (_axi4map_1_auto_in_r_bits_id),
    .auto_out_1_r_bits_data   (_axi4map_1_auto_in_r_bits_data),
    .auto_out_1_r_bits_resp   (_axi4map_1_auto_in_r_bits_resp),
    .auto_out_1_r_bits_last   (_axi4map_1_auto_in_r_bits_last),
    .auto_out_0_aw_valid      (_imsics_fromMem_xbar_auto_out_0_aw_valid),
    .auto_out_0_aw_bits_id    (_imsics_fromMem_xbar_auto_out_0_aw_bits_id),
    .auto_out_0_aw_bits_addr  (_imsics_fromMem_xbar_auto_out_0_aw_bits_addr),
    .auto_out_0_aw_bits_len   (_imsics_fromMem_xbar_auto_out_0_aw_bits_len),
    .auto_out_0_aw_bits_size  (_imsics_fromMem_xbar_auto_out_0_aw_bits_size),
    .auto_out_0_aw_bits_burst (_imsics_fromMem_xbar_auto_out_0_aw_bits_burst),
    .auto_out_0_aw_bits_lock  (_imsics_fromMem_xbar_auto_out_0_aw_bits_lock),
    .auto_out_0_aw_bits_cache (_imsics_fromMem_xbar_auto_out_0_aw_bits_cache),
    .auto_out_0_aw_bits_prot  (_imsics_fromMem_xbar_auto_out_0_aw_bits_prot),
    .auto_out_0_aw_bits_qos   (_imsics_fromMem_xbar_auto_out_0_aw_bits_qos),
    .auto_out_0_w_valid       (_imsics_fromMem_xbar_auto_out_0_w_valid),
    .auto_out_0_w_bits_data   (_imsics_fromMem_xbar_auto_out_0_w_bits_data),
    .auto_out_0_w_bits_strb   (_imsics_fromMem_xbar_auto_out_0_w_bits_strb),
    .auto_out_0_w_bits_last   (_imsics_fromMem_xbar_auto_out_0_w_bits_last),
    .auto_out_0_b_ready       (_imsics_fromMem_xbar_auto_out_0_b_ready),
    .auto_out_0_b_valid       (_axi4map_auto_in_b_valid),
    .auto_out_0_b_bits_id     (_axi4map_auto_in_b_bits_id),
    .auto_out_0_b_bits_resp   (_axi4map_auto_in_b_bits_resp),
    .auto_out_0_ar_ready      (_axi4map_auto_in_ar_ready),
    .auto_out_0_ar_valid      (_imsics_fromMem_xbar_auto_out_0_ar_valid),
    .auto_out_0_ar_bits_id    (_imsics_fromMem_xbar_auto_out_0_ar_bits_id),
    .auto_out_0_ar_bits_addr  (_imsics_fromMem_xbar_auto_out_0_ar_bits_addr),
    .auto_out_0_ar_bits_len   (_imsics_fromMem_xbar_auto_out_0_ar_bits_len),
    .auto_out_0_ar_bits_size  (_imsics_fromMem_xbar_auto_out_0_ar_bits_size),
    .auto_out_0_ar_bits_burst (_imsics_fromMem_xbar_auto_out_0_ar_bits_burst),
    .auto_out_0_ar_bits_lock  (_imsics_fromMem_xbar_auto_out_0_ar_bits_lock),
    .auto_out_0_ar_bits_cache (_imsics_fromMem_xbar_auto_out_0_ar_bits_cache),
    .auto_out_0_ar_bits_prot  (_imsics_fromMem_xbar_auto_out_0_ar_bits_prot),
    .auto_out_0_ar_bits_qos   (_imsics_fromMem_xbar_auto_out_0_ar_bits_qos),
    .auto_out_0_r_ready       (_imsics_fromMem_xbar_auto_out_0_r_ready),
    .auto_out_0_r_valid       (_axi4map_auto_in_r_valid),
    .auto_out_0_r_bits_id     (_axi4map_auto_in_r_bits_id),
    .auto_out_0_r_bits_data   (_axi4map_auto_in_r_bits_data),
    .auto_out_0_r_bits_resp   (_axi4map_auto_in_r_bits_resp),
    .auto_out_0_r_bits_last   (_axi4map_auto_in_r_bits_last)
  );
  AXI4Map axi4map (
    .auto_in_aw_valid       (_imsics_fromMem_xbar_auto_out_0_aw_valid),
    .auto_in_aw_bits_id     (_imsics_fromMem_xbar_auto_out_0_aw_bits_id),
    .auto_in_aw_bits_addr   (_imsics_fromMem_xbar_auto_out_0_aw_bits_addr),
    .auto_in_aw_bits_len    (_imsics_fromMem_xbar_auto_out_0_aw_bits_len),
    .auto_in_aw_bits_size   (_imsics_fromMem_xbar_auto_out_0_aw_bits_size),
    .auto_in_aw_bits_burst  (_imsics_fromMem_xbar_auto_out_0_aw_bits_burst),
    .auto_in_aw_bits_lock   (_imsics_fromMem_xbar_auto_out_0_aw_bits_lock),
    .auto_in_aw_bits_cache  (_imsics_fromMem_xbar_auto_out_0_aw_bits_cache),
    .auto_in_aw_bits_prot   (_imsics_fromMem_xbar_auto_out_0_aw_bits_prot),
    .auto_in_aw_bits_qos    (_imsics_fromMem_xbar_auto_out_0_aw_bits_qos),
    .auto_in_w_valid        (_imsics_fromMem_xbar_auto_out_0_w_valid),
    .auto_in_w_bits_data    (_imsics_fromMem_xbar_auto_out_0_w_bits_data),
    .auto_in_w_bits_strb    (_imsics_fromMem_xbar_auto_out_0_w_bits_strb),
    .auto_in_w_bits_last    (_imsics_fromMem_xbar_auto_out_0_w_bits_last),
    .auto_in_b_ready        (_imsics_fromMem_xbar_auto_out_0_b_ready),
    .auto_in_b_valid        (_axi4map_auto_in_b_valid),
    .auto_in_b_bits_id      (_axi4map_auto_in_b_bits_id),
    .auto_in_b_bits_resp    (_axi4map_auto_in_b_bits_resp),
    .auto_in_ar_ready       (_axi4map_auto_in_ar_ready),
    .auto_in_ar_valid       (_imsics_fromMem_xbar_auto_out_0_ar_valid),
    .auto_in_ar_bits_id     (_imsics_fromMem_xbar_auto_out_0_ar_bits_id),
    .auto_in_ar_bits_addr   (_imsics_fromMem_xbar_auto_out_0_ar_bits_addr),
    .auto_in_ar_bits_len    (_imsics_fromMem_xbar_auto_out_0_ar_bits_len),
    .auto_in_ar_bits_size   (_imsics_fromMem_xbar_auto_out_0_ar_bits_size),
    .auto_in_ar_bits_burst  (_imsics_fromMem_xbar_auto_out_0_ar_bits_burst),
    .auto_in_ar_bits_lock   (_imsics_fromMem_xbar_auto_out_0_ar_bits_lock),
    .auto_in_ar_bits_cache  (_imsics_fromMem_xbar_auto_out_0_ar_bits_cache),
    .auto_in_ar_bits_prot   (_imsics_fromMem_xbar_auto_out_0_ar_bits_prot),
    .auto_in_ar_bits_qos    (_imsics_fromMem_xbar_auto_out_0_ar_bits_qos),
    .auto_in_r_ready        (_imsics_fromMem_xbar_auto_out_0_r_ready),
    .auto_in_r_valid        (_axi4map_auto_in_r_valid),
    .auto_in_r_bits_id      (_axi4map_auto_in_r_bits_id),
    .auto_in_r_bits_data    (_axi4map_auto_in_r_bits_data),
    .auto_in_r_bits_resp    (_axi4map_auto_in_r_bits_resp),
    .auto_in_r_bits_last    (_axi4map_auto_in_r_bits_last),
    .auto_out_aw_valid      (_axi4map_auto_out_aw_valid),
    .auto_out_aw_bits_id    (_axi4map_auto_out_aw_bits_id),
    .auto_out_aw_bits_addr  (_axi4map_auto_out_aw_bits_addr),
    .auto_out_aw_bits_len   (_axi4map_auto_out_aw_bits_len),
    .auto_out_aw_bits_size  (_axi4map_auto_out_aw_bits_size),
    .auto_out_aw_bits_burst (_axi4map_auto_out_aw_bits_burst),
    .auto_out_aw_bits_lock  (_axi4map_auto_out_aw_bits_lock),
    .auto_out_aw_bits_cache (_axi4map_auto_out_aw_bits_cache),
    .auto_out_aw_bits_prot  (_axi4map_auto_out_aw_bits_prot),
    .auto_out_aw_bits_qos   (_axi4map_auto_out_aw_bits_qos),
    .auto_out_w_valid       (_axi4map_auto_out_w_valid),
    .auto_out_w_bits_data   (_axi4map_auto_out_w_bits_data),
    .auto_out_w_bits_strb   (_axi4map_auto_out_w_bits_strb),
    .auto_out_w_bits_last   (_axi4map_auto_out_w_bits_last),
    .auto_out_b_ready       (_axi4map_auto_out_b_ready),
    .auto_out_b_valid       (_imsic_auto_axireg_axireg_axi4xbar_in_b_valid),
    .auto_out_b_bits_id     (_imsic_auto_axireg_axireg_axi4xbar_in_b_bits_id),
    .auto_out_b_bits_resp   (_imsic_auto_axireg_axireg_axi4xbar_in_b_bits_resp),
    .auto_out_ar_ready      (_imsic_auto_axireg_axireg_axi4xbar_in_ar_ready),
    .auto_out_ar_valid      (_axi4map_auto_out_ar_valid),
    .auto_out_ar_bits_id    (_axi4map_auto_out_ar_bits_id),
    .auto_out_ar_bits_addr  (_axi4map_auto_out_ar_bits_addr),
    .auto_out_ar_bits_len   (_axi4map_auto_out_ar_bits_len),
    .auto_out_ar_bits_size  (_axi4map_auto_out_ar_bits_size),
    .auto_out_ar_bits_burst (_axi4map_auto_out_ar_bits_burst),
    .auto_out_ar_bits_lock  (_axi4map_auto_out_ar_bits_lock),
    .auto_out_ar_bits_cache (_axi4map_auto_out_ar_bits_cache),
    .auto_out_ar_bits_prot  (_axi4map_auto_out_ar_bits_prot),
    .auto_out_ar_bits_qos   (_axi4map_auto_out_ar_bits_qos),
    .auto_out_r_ready       (_axi4map_auto_out_r_ready),
    .auto_out_r_valid       (_imsic_auto_axireg_axireg_axi4xbar_in_r_valid),
    .auto_out_r_bits_id     (_imsic_auto_axireg_axireg_axi4xbar_in_r_bits_id),
    .auto_out_r_bits_data   (_imsic_auto_axireg_axireg_axi4xbar_in_r_bits_data),
    .auto_out_r_bits_resp   (_imsic_auto_axireg_axireg_axi4xbar_in_r_bits_resp),
    .auto_out_r_bits_last   (_imsic_auto_axireg_axireg_axi4xbar_in_r_bits_last)
  );
  AXI4IMSIC imsic (
    .clock                                        (clock),
    .reset                                        (reset),
    .auto_axireg_axireg_axi4xbar_in_aw_valid      (_axi4map_auto_out_aw_valid),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_id    (_axi4map_auto_out_aw_bits_id),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_addr  (_axi4map_auto_out_aw_bits_addr),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_len   (_axi4map_auto_out_aw_bits_len),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_size  (_axi4map_auto_out_aw_bits_size),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_burst (_axi4map_auto_out_aw_bits_burst),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_lock  (_axi4map_auto_out_aw_bits_lock),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_cache (_axi4map_auto_out_aw_bits_cache),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_prot  (_axi4map_auto_out_aw_bits_prot),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_qos   (_axi4map_auto_out_aw_bits_qos),
    .auto_axireg_axireg_axi4xbar_in_w_valid       (_axi4map_auto_out_w_valid),
    .auto_axireg_axireg_axi4xbar_in_w_bits_data   (_axi4map_auto_out_w_bits_data),
    .auto_axireg_axireg_axi4xbar_in_w_bits_strb   (_axi4map_auto_out_w_bits_strb),
    .auto_axireg_axireg_axi4xbar_in_w_bits_last   (_axi4map_auto_out_w_bits_last),
    .auto_axireg_axireg_axi4xbar_in_b_ready       (_axi4map_auto_out_b_ready),
    .auto_axireg_axireg_axi4xbar_in_b_valid
      (_imsic_auto_axireg_axireg_axi4xbar_in_b_valid),
    .auto_axireg_axireg_axi4xbar_in_b_bits_id
      (_imsic_auto_axireg_axireg_axi4xbar_in_b_bits_id),
    .auto_axireg_axireg_axi4xbar_in_b_bits_resp
      (_imsic_auto_axireg_axireg_axi4xbar_in_b_bits_resp),
    .auto_axireg_axireg_axi4xbar_in_ar_ready
      (_imsic_auto_axireg_axireg_axi4xbar_in_ar_ready),
    .auto_axireg_axireg_axi4xbar_in_ar_valid      (_axi4map_auto_out_ar_valid),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_id    (_axi4map_auto_out_ar_bits_id),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_addr  (_axi4map_auto_out_ar_bits_addr),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_len   (_axi4map_auto_out_ar_bits_len),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_size  (_axi4map_auto_out_ar_bits_size),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_burst (_axi4map_auto_out_ar_bits_burst),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_lock  (_axi4map_auto_out_ar_bits_lock),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_cache (_axi4map_auto_out_ar_bits_cache),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_prot  (_axi4map_auto_out_ar_bits_prot),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_qos   (_axi4map_auto_out_ar_bits_qos),
    .auto_axireg_axireg_axi4xbar_in_r_ready       (_axi4map_auto_out_r_ready),
    .auto_axireg_axireg_axi4xbar_in_r_valid
      (_imsic_auto_axireg_axireg_axi4xbar_in_r_valid),
    .auto_axireg_axireg_axi4xbar_in_r_bits_id
      (_imsic_auto_axireg_axireg_axi4xbar_in_r_bits_id),
    .auto_axireg_axireg_axi4xbar_in_r_bits_data
      (_imsic_auto_axireg_axireg_axi4xbar_in_r_bits_data),
    .auto_axireg_axireg_axi4xbar_in_r_bits_resp
      (_imsic_auto_axireg_axireg_axi4xbar_in_r_bits_resp),
    .auto_axireg_axireg_axi4xbar_in_r_bits_last
      (_imsic_auto_axireg_axireg_axi4xbar_in_r_bits_last),
    .toCSR_rdata_valid                            (toCSR0_rdata_valid),
    .toCSR_rdata_bits                             (toCSR0_rdata_bits),
    .toCSR_illegal                                (toCSR0_illegal),
    .toCSR_pendings                               (toCSR0_pendings),
    .toCSR_topeis_0                               (toCSR0_topeis_0),
    .toCSR_topeis_1                               (toCSR0_topeis_1),
    .toCSR_topeis_2                               (toCSR0_topeis_2),
    .fromCSR_addr_valid                           (fromCSR0_addr_valid),
    .fromCSR_addr_bits                            (fromCSR0_addr_bits),
    .fromCSR_virt                                 (fromCSR0_virt),
    .fromCSR_priv                                 (fromCSR0_priv),
    .fromCSR_vgein                                (fromCSR0_vgein),
    .fromCSR_wdata_valid                          (fromCSR0_wdata_valid),
    .fromCSR_wdata_bits_op                        (fromCSR0_wdata_bits_op),
    .fromCSR_wdata_bits_data                      (fromCSR0_wdata_bits_data),
    .fromCSR_claims_0                             (fromCSR0_claims_0),
    .fromCSR_claims_1                             (fromCSR0_claims_1),
    .fromCSR_claims_2                             (fromCSR0_claims_2),
    .soc_clock                                    (clock),
    .soc_reset                                    (reset)
  );
  AXI4Map_2 axi4map_1 (
    .auto_in_aw_valid       (_imsics_fromMem_xbar_auto_out_1_aw_valid),
    .auto_in_aw_bits_id     (_imsics_fromMem_xbar_auto_out_1_aw_bits_id),
    .auto_in_aw_bits_addr   (_imsics_fromMem_xbar_auto_out_1_aw_bits_addr),
    .auto_in_aw_bits_len    (_imsics_fromMem_xbar_auto_out_1_aw_bits_len),
    .auto_in_aw_bits_size   (_imsics_fromMem_xbar_auto_out_1_aw_bits_size),
    .auto_in_aw_bits_burst  (_imsics_fromMem_xbar_auto_out_1_aw_bits_burst),
    .auto_in_aw_bits_lock   (_imsics_fromMem_xbar_auto_out_1_aw_bits_lock),
    .auto_in_aw_bits_cache  (_imsics_fromMem_xbar_auto_out_1_aw_bits_cache),
    .auto_in_aw_bits_prot   (_imsics_fromMem_xbar_auto_out_1_aw_bits_prot),
    .auto_in_aw_bits_qos    (_imsics_fromMem_xbar_auto_out_1_aw_bits_qos),
    .auto_in_w_valid        (_imsics_fromMem_xbar_auto_out_1_w_valid),
    .auto_in_w_bits_data    (_imsics_fromMem_xbar_auto_out_1_w_bits_data),
    .auto_in_w_bits_strb    (_imsics_fromMem_xbar_auto_out_1_w_bits_strb),
    .auto_in_w_bits_last    (_imsics_fromMem_xbar_auto_out_1_w_bits_last),
    .auto_in_b_ready        (_imsics_fromMem_xbar_auto_out_1_b_ready),
    .auto_in_b_valid        (_axi4map_1_auto_in_b_valid),
    .auto_in_b_bits_id      (_axi4map_1_auto_in_b_bits_id),
    .auto_in_b_bits_resp    (_axi4map_1_auto_in_b_bits_resp),
    .auto_in_ar_ready       (_axi4map_1_auto_in_ar_ready),
    .auto_in_ar_valid       (_imsics_fromMem_xbar_auto_out_1_ar_valid),
    .auto_in_ar_bits_id     (_imsics_fromMem_xbar_auto_out_1_ar_bits_id),
    .auto_in_ar_bits_addr   (_imsics_fromMem_xbar_auto_out_1_ar_bits_addr),
    .auto_in_ar_bits_len    (_imsics_fromMem_xbar_auto_out_1_ar_bits_len),
    .auto_in_ar_bits_size   (_imsics_fromMem_xbar_auto_out_1_ar_bits_size),
    .auto_in_ar_bits_burst  (_imsics_fromMem_xbar_auto_out_1_ar_bits_burst),
    .auto_in_ar_bits_lock   (_imsics_fromMem_xbar_auto_out_1_ar_bits_lock),
    .auto_in_ar_bits_cache  (_imsics_fromMem_xbar_auto_out_1_ar_bits_cache),
    .auto_in_ar_bits_prot   (_imsics_fromMem_xbar_auto_out_1_ar_bits_prot),
    .auto_in_ar_bits_qos    (_imsics_fromMem_xbar_auto_out_1_ar_bits_qos),
    .auto_in_r_ready        (_imsics_fromMem_xbar_auto_out_1_r_ready),
    .auto_in_r_valid        (_axi4map_1_auto_in_r_valid),
    .auto_in_r_bits_id      (_axi4map_1_auto_in_r_bits_id),
    .auto_in_r_bits_data    (_axi4map_1_auto_in_r_bits_data),
    .auto_in_r_bits_resp    (_axi4map_1_auto_in_r_bits_resp),
    .auto_in_r_bits_last    (_axi4map_1_auto_in_r_bits_last),
    .auto_out_aw_valid      (_axi4map_1_auto_out_aw_valid),
    .auto_out_aw_bits_id    (_axi4map_1_auto_out_aw_bits_id),
    .auto_out_aw_bits_addr  (_axi4map_1_auto_out_aw_bits_addr),
    .auto_out_aw_bits_len   (_axi4map_1_auto_out_aw_bits_len),
    .auto_out_aw_bits_size  (_axi4map_1_auto_out_aw_bits_size),
    .auto_out_aw_bits_burst (_axi4map_1_auto_out_aw_bits_burst),
    .auto_out_aw_bits_lock  (_axi4map_1_auto_out_aw_bits_lock),
    .auto_out_aw_bits_cache (_axi4map_1_auto_out_aw_bits_cache),
    .auto_out_aw_bits_prot  (_axi4map_1_auto_out_aw_bits_prot),
    .auto_out_aw_bits_qos   (_axi4map_1_auto_out_aw_bits_qos),
    .auto_out_w_valid       (_axi4map_1_auto_out_w_valid),
    .auto_out_w_bits_data   (_axi4map_1_auto_out_w_bits_data),
    .auto_out_w_bits_strb   (_axi4map_1_auto_out_w_bits_strb),
    .auto_out_w_bits_last   (_axi4map_1_auto_out_w_bits_last),
    .auto_out_b_ready       (_axi4map_1_auto_out_b_ready),
    .auto_out_b_valid       (_imsic_1_auto_axireg_axireg_axi4xbar_in_b_valid),
    .auto_out_b_bits_id     (_imsic_1_auto_axireg_axireg_axi4xbar_in_b_bits_id),
    .auto_out_b_bits_resp   (_imsic_1_auto_axireg_axireg_axi4xbar_in_b_bits_resp),
    .auto_out_ar_ready      (_imsic_1_auto_axireg_axireg_axi4xbar_in_ar_ready),
    .auto_out_ar_valid      (_axi4map_1_auto_out_ar_valid),
    .auto_out_ar_bits_id    (_axi4map_1_auto_out_ar_bits_id),
    .auto_out_ar_bits_addr  (_axi4map_1_auto_out_ar_bits_addr),
    .auto_out_ar_bits_len   (_axi4map_1_auto_out_ar_bits_len),
    .auto_out_ar_bits_size  (_axi4map_1_auto_out_ar_bits_size),
    .auto_out_ar_bits_burst (_axi4map_1_auto_out_ar_bits_burst),
    .auto_out_ar_bits_lock  (_axi4map_1_auto_out_ar_bits_lock),
    .auto_out_ar_bits_cache (_axi4map_1_auto_out_ar_bits_cache),
    .auto_out_ar_bits_prot  (_axi4map_1_auto_out_ar_bits_prot),
    .auto_out_ar_bits_qos   (_axi4map_1_auto_out_ar_bits_qos),
    .auto_out_r_ready       (_axi4map_1_auto_out_r_ready),
    .auto_out_r_valid       (_imsic_1_auto_axireg_axireg_axi4xbar_in_r_valid),
    .auto_out_r_bits_id     (_imsic_1_auto_axireg_axireg_axi4xbar_in_r_bits_id),
    .auto_out_r_bits_data   (_imsic_1_auto_axireg_axireg_axi4xbar_in_r_bits_data),
    .auto_out_r_bits_resp   (_imsic_1_auto_axireg_axireg_axi4xbar_in_r_bits_resp),
    .auto_out_r_bits_last   (_imsic_1_auto_axireg_axireg_axi4xbar_in_r_bits_last)
  );
  AXI4IMSIC imsic_1 (
    .clock                                        (clock),
    .reset                                        (reset),
    .auto_axireg_axireg_axi4xbar_in_aw_valid      (_axi4map_1_auto_out_aw_valid),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_id    (_axi4map_1_auto_out_aw_bits_id),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_addr  (_axi4map_1_auto_out_aw_bits_addr),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_len   (_axi4map_1_auto_out_aw_bits_len),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_size  (_axi4map_1_auto_out_aw_bits_size),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_burst (_axi4map_1_auto_out_aw_bits_burst),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_lock  (_axi4map_1_auto_out_aw_bits_lock),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_cache (_axi4map_1_auto_out_aw_bits_cache),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_prot  (_axi4map_1_auto_out_aw_bits_prot),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_qos   (_axi4map_1_auto_out_aw_bits_qos),
    .auto_axireg_axireg_axi4xbar_in_w_valid       (_axi4map_1_auto_out_w_valid),
    .auto_axireg_axireg_axi4xbar_in_w_bits_data   (_axi4map_1_auto_out_w_bits_data),
    .auto_axireg_axireg_axi4xbar_in_w_bits_strb   (_axi4map_1_auto_out_w_bits_strb),
    .auto_axireg_axireg_axi4xbar_in_w_bits_last   (_axi4map_1_auto_out_w_bits_last),
    .auto_axireg_axireg_axi4xbar_in_b_ready       (_axi4map_1_auto_out_b_ready),
    .auto_axireg_axireg_axi4xbar_in_b_valid
      (_imsic_1_auto_axireg_axireg_axi4xbar_in_b_valid),
    .auto_axireg_axireg_axi4xbar_in_b_bits_id
      (_imsic_1_auto_axireg_axireg_axi4xbar_in_b_bits_id),
    .auto_axireg_axireg_axi4xbar_in_b_bits_resp
      (_imsic_1_auto_axireg_axireg_axi4xbar_in_b_bits_resp),
    .auto_axireg_axireg_axi4xbar_in_ar_ready
      (_imsic_1_auto_axireg_axireg_axi4xbar_in_ar_ready),
    .auto_axireg_axireg_axi4xbar_in_ar_valid      (_axi4map_1_auto_out_ar_valid),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_id    (_axi4map_1_auto_out_ar_bits_id),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_addr  (_axi4map_1_auto_out_ar_bits_addr),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_len   (_axi4map_1_auto_out_ar_bits_len),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_size  (_axi4map_1_auto_out_ar_bits_size),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_burst (_axi4map_1_auto_out_ar_bits_burst),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_lock  (_axi4map_1_auto_out_ar_bits_lock),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_cache (_axi4map_1_auto_out_ar_bits_cache),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_prot  (_axi4map_1_auto_out_ar_bits_prot),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_qos   (_axi4map_1_auto_out_ar_bits_qos),
    .auto_axireg_axireg_axi4xbar_in_r_ready       (_axi4map_1_auto_out_r_ready),
    .auto_axireg_axireg_axi4xbar_in_r_valid
      (_imsic_1_auto_axireg_axireg_axi4xbar_in_r_valid),
    .auto_axireg_axireg_axi4xbar_in_r_bits_id
      (_imsic_1_auto_axireg_axireg_axi4xbar_in_r_bits_id),
    .auto_axireg_axireg_axi4xbar_in_r_bits_data
      (_imsic_1_auto_axireg_axireg_axi4xbar_in_r_bits_data),
    .auto_axireg_axireg_axi4xbar_in_r_bits_resp
      (_imsic_1_auto_axireg_axireg_axi4xbar_in_r_bits_resp),
    .auto_axireg_axireg_axi4xbar_in_r_bits_last
      (_imsic_1_auto_axireg_axireg_axi4xbar_in_r_bits_last),
    .toCSR_rdata_valid                            (toCSR1_rdata_valid),
    .toCSR_rdata_bits                             (toCSR1_rdata_bits),
    .toCSR_illegal                                (toCSR1_illegal),
    .toCSR_pendings                               (toCSR1_pendings),
    .toCSR_topeis_0                               (toCSR1_topeis_0),
    .toCSR_topeis_1                               (toCSR1_topeis_1),
    .toCSR_topeis_2                               (toCSR1_topeis_2),
    .fromCSR_addr_valid                           (fromCSR1_addr_valid),
    .fromCSR_addr_bits                            (fromCSR1_addr_bits),
    .fromCSR_virt                                 (fromCSR1_virt),
    .fromCSR_priv                                 (fromCSR1_priv),
    .fromCSR_vgein                                (fromCSR1_vgein),
    .fromCSR_wdata_valid                          (fromCSR1_wdata_valid),
    .fromCSR_wdata_bits_op                        (fromCSR1_wdata_bits_op),
    .fromCSR_wdata_bits_data                      (fromCSR1_wdata_bits_data),
    .fromCSR_claims_0                             (fromCSR1_claims_0),
    .fromCSR_claims_1                             (fromCSR1_claims_1),
    .fromCSR_claims_2                             (fromCSR1_claims_2),
    .soc_clock                                    (clock),
    .soc_reset                                    (reset)
  );
  AXI4Map_4 axi4map_2 (
    .auto_in_aw_valid       (_imsics_fromMem_xbar_auto_out_2_aw_valid),
    .auto_in_aw_bits_id     (_imsics_fromMem_xbar_auto_out_2_aw_bits_id),
    .auto_in_aw_bits_addr   (_imsics_fromMem_xbar_auto_out_2_aw_bits_addr),
    .auto_in_aw_bits_len    (_imsics_fromMem_xbar_auto_out_2_aw_bits_len),
    .auto_in_aw_bits_size   (_imsics_fromMem_xbar_auto_out_2_aw_bits_size),
    .auto_in_aw_bits_burst  (_imsics_fromMem_xbar_auto_out_2_aw_bits_burst),
    .auto_in_aw_bits_lock   (_imsics_fromMem_xbar_auto_out_2_aw_bits_lock),
    .auto_in_aw_bits_cache  (_imsics_fromMem_xbar_auto_out_2_aw_bits_cache),
    .auto_in_aw_bits_prot   (_imsics_fromMem_xbar_auto_out_2_aw_bits_prot),
    .auto_in_aw_bits_qos    (_imsics_fromMem_xbar_auto_out_2_aw_bits_qos),
    .auto_in_w_valid        (_imsics_fromMem_xbar_auto_out_2_w_valid),
    .auto_in_w_bits_data    (_imsics_fromMem_xbar_auto_out_2_w_bits_data),
    .auto_in_w_bits_strb    (_imsics_fromMem_xbar_auto_out_2_w_bits_strb),
    .auto_in_w_bits_last    (_imsics_fromMem_xbar_auto_out_2_w_bits_last),
    .auto_in_b_ready        (_imsics_fromMem_xbar_auto_out_2_b_ready),
    .auto_in_b_valid        (_axi4map_2_auto_in_b_valid),
    .auto_in_b_bits_id      (_axi4map_2_auto_in_b_bits_id),
    .auto_in_b_bits_resp    (_axi4map_2_auto_in_b_bits_resp),
    .auto_in_ar_ready       (_axi4map_2_auto_in_ar_ready),
    .auto_in_ar_valid       (_imsics_fromMem_xbar_auto_out_2_ar_valid),
    .auto_in_ar_bits_id     (_imsics_fromMem_xbar_auto_out_2_ar_bits_id),
    .auto_in_ar_bits_addr   (_imsics_fromMem_xbar_auto_out_2_ar_bits_addr),
    .auto_in_ar_bits_len    (_imsics_fromMem_xbar_auto_out_2_ar_bits_len),
    .auto_in_ar_bits_size   (_imsics_fromMem_xbar_auto_out_2_ar_bits_size),
    .auto_in_ar_bits_burst  (_imsics_fromMem_xbar_auto_out_2_ar_bits_burst),
    .auto_in_ar_bits_lock   (_imsics_fromMem_xbar_auto_out_2_ar_bits_lock),
    .auto_in_ar_bits_cache  (_imsics_fromMem_xbar_auto_out_2_ar_bits_cache),
    .auto_in_ar_bits_prot   (_imsics_fromMem_xbar_auto_out_2_ar_bits_prot),
    .auto_in_ar_bits_qos    (_imsics_fromMem_xbar_auto_out_2_ar_bits_qos),
    .auto_in_r_ready        (_imsics_fromMem_xbar_auto_out_2_r_ready),
    .auto_in_r_valid        (_axi4map_2_auto_in_r_valid),
    .auto_in_r_bits_id      (_axi4map_2_auto_in_r_bits_id),
    .auto_in_r_bits_data    (_axi4map_2_auto_in_r_bits_data),
    .auto_in_r_bits_resp    (_axi4map_2_auto_in_r_bits_resp),
    .auto_in_r_bits_last    (_axi4map_2_auto_in_r_bits_last),
    .auto_out_aw_valid      (_axi4map_2_auto_out_aw_valid),
    .auto_out_aw_bits_id    (_axi4map_2_auto_out_aw_bits_id),
    .auto_out_aw_bits_addr  (_axi4map_2_auto_out_aw_bits_addr),
    .auto_out_aw_bits_len   (_axi4map_2_auto_out_aw_bits_len),
    .auto_out_aw_bits_size  (_axi4map_2_auto_out_aw_bits_size),
    .auto_out_aw_bits_burst (_axi4map_2_auto_out_aw_bits_burst),
    .auto_out_aw_bits_lock  (_axi4map_2_auto_out_aw_bits_lock),
    .auto_out_aw_bits_cache (_axi4map_2_auto_out_aw_bits_cache),
    .auto_out_aw_bits_prot  (_axi4map_2_auto_out_aw_bits_prot),
    .auto_out_aw_bits_qos   (_axi4map_2_auto_out_aw_bits_qos),
    .auto_out_w_valid       (_axi4map_2_auto_out_w_valid),
    .auto_out_w_bits_data   (_axi4map_2_auto_out_w_bits_data),
    .auto_out_w_bits_strb   (_axi4map_2_auto_out_w_bits_strb),
    .auto_out_w_bits_last   (_axi4map_2_auto_out_w_bits_last),
    .auto_out_b_ready       (_axi4map_2_auto_out_b_ready),
    .auto_out_b_valid       (_imsic_2_auto_axireg_axireg_axi4xbar_in_b_valid),
    .auto_out_b_bits_id     (_imsic_2_auto_axireg_axireg_axi4xbar_in_b_bits_id),
    .auto_out_b_bits_resp   (_imsic_2_auto_axireg_axireg_axi4xbar_in_b_bits_resp),
    .auto_out_ar_ready      (_imsic_2_auto_axireg_axireg_axi4xbar_in_ar_ready),
    .auto_out_ar_valid      (_axi4map_2_auto_out_ar_valid),
    .auto_out_ar_bits_id    (_axi4map_2_auto_out_ar_bits_id),
    .auto_out_ar_bits_addr  (_axi4map_2_auto_out_ar_bits_addr),
    .auto_out_ar_bits_len   (_axi4map_2_auto_out_ar_bits_len),
    .auto_out_ar_bits_size  (_axi4map_2_auto_out_ar_bits_size),
    .auto_out_ar_bits_burst (_axi4map_2_auto_out_ar_bits_burst),
    .auto_out_ar_bits_lock  (_axi4map_2_auto_out_ar_bits_lock),
    .auto_out_ar_bits_cache (_axi4map_2_auto_out_ar_bits_cache),
    .auto_out_ar_bits_prot  (_axi4map_2_auto_out_ar_bits_prot),
    .auto_out_ar_bits_qos   (_axi4map_2_auto_out_ar_bits_qos),
    .auto_out_r_ready       (_axi4map_2_auto_out_r_ready),
    .auto_out_r_valid       (_imsic_2_auto_axireg_axireg_axi4xbar_in_r_valid),
    .auto_out_r_bits_id     (_imsic_2_auto_axireg_axireg_axi4xbar_in_r_bits_id),
    .auto_out_r_bits_data   (_imsic_2_auto_axireg_axireg_axi4xbar_in_r_bits_data),
    .auto_out_r_bits_resp   (_imsic_2_auto_axireg_axireg_axi4xbar_in_r_bits_resp),
    .auto_out_r_bits_last   (_imsic_2_auto_axireg_axireg_axi4xbar_in_r_bits_last)
  );
  AXI4IMSIC imsic_2 (
    .clock                                        (clock),
    .reset                                        (reset),
    .auto_axireg_axireg_axi4xbar_in_aw_valid      (_axi4map_2_auto_out_aw_valid),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_id    (_axi4map_2_auto_out_aw_bits_id),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_addr  (_axi4map_2_auto_out_aw_bits_addr),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_len   (_axi4map_2_auto_out_aw_bits_len),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_size  (_axi4map_2_auto_out_aw_bits_size),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_burst (_axi4map_2_auto_out_aw_bits_burst),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_lock  (_axi4map_2_auto_out_aw_bits_lock),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_cache (_axi4map_2_auto_out_aw_bits_cache),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_prot  (_axi4map_2_auto_out_aw_bits_prot),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_qos   (_axi4map_2_auto_out_aw_bits_qos),
    .auto_axireg_axireg_axi4xbar_in_w_valid       (_axi4map_2_auto_out_w_valid),
    .auto_axireg_axireg_axi4xbar_in_w_bits_data   (_axi4map_2_auto_out_w_bits_data),
    .auto_axireg_axireg_axi4xbar_in_w_bits_strb   (_axi4map_2_auto_out_w_bits_strb),
    .auto_axireg_axireg_axi4xbar_in_w_bits_last   (_axi4map_2_auto_out_w_bits_last),
    .auto_axireg_axireg_axi4xbar_in_b_ready       (_axi4map_2_auto_out_b_ready),
    .auto_axireg_axireg_axi4xbar_in_b_valid
      (_imsic_2_auto_axireg_axireg_axi4xbar_in_b_valid),
    .auto_axireg_axireg_axi4xbar_in_b_bits_id
      (_imsic_2_auto_axireg_axireg_axi4xbar_in_b_bits_id),
    .auto_axireg_axireg_axi4xbar_in_b_bits_resp
      (_imsic_2_auto_axireg_axireg_axi4xbar_in_b_bits_resp),
    .auto_axireg_axireg_axi4xbar_in_ar_ready
      (_imsic_2_auto_axireg_axireg_axi4xbar_in_ar_ready),
    .auto_axireg_axireg_axi4xbar_in_ar_valid      (_axi4map_2_auto_out_ar_valid),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_id    (_axi4map_2_auto_out_ar_bits_id),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_addr  (_axi4map_2_auto_out_ar_bits_addr),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_len   (_axi4map_2_auto_out_ar_bits_len),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_size  (_axi4map_2_auto_out_ar_bits_size),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_burst (_axi4map_2_auto_out_ar_bits_burst),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_lock  (_axi4map_2_auto_out_ar_bits_lock),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_cache (_axi4map_2_auto_out_ar_bits_cache),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_prot  (_axi4map_2_auto_out_ar_bits_prot),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_qos   (_axi4map_2_auto_out_ar_bits_qos),
    .auto_axireg_axireg_axi4xbar_in_r_ready       (_axi4map_2_auto_out_r_ready),
    .auto_axireg_axireg_axi4xbar_in_r_valid
      (_imsic_2_auto_axireg_axireg_axi4xbar_in_r_valid),
    .auto_axireg_axireg_axi4xbar_in_r_bits_id
      (_imsic_2_auto_axireg_axireg_axi4xbar_in_r_bits_id),
    .auto_axireg_axireg_axi4xbar_in_r_bits_data
      (_imsic_2_auto_axireg_axireg_axi4xbar_in_r_bits_data),
    .auto_axireg_axireg_axi4xbar_in_r_bits_resp
      (_imsic_2_auto_axireg_axireg_axi4xbar_in_r_bits_resp),
    .auto_axireg_axireg_axi4xbar_in_r_bits_last
      (_imsic_2_auto_axireg_axireg_axi4xbar_in_r_bits_last),
    .toCSR_rdata_valid                            (toCSR2_rdata_valid),
    .toCSR_rdata_bits                             (toCSR2_rdata_bits),
    .toCSR_illegal                                (toCSR2_illegal),
    .toCSR_pendings                               (toCSR2_pendings),
    .toCSR_topeis_0                               (toCSR2_topeis_0),
    .toCSR_topeis_1                               (toCSR2_topeis_1),
    .toCSR_topeis_2                               (toCSR2_topeis_2),
    .fromCSR_addr_valid                           (fromCSR2_addr_valid),
    .fromCSR_addr_bits                            (fromCSR2_addr_bits),
    .fromCSR_virt                                 (fromCSR2_virt),
    .fromCSR_priv                                 (fromCSR2_priv),
    .fromCSR_vgein                                (fromCSR2_vgein),
    .fromCSR_wdata_valid                          (fromCSR2_wdata_valid),
    .fromCSR_wdata_bits_op                        (fromCSR2_wdata_bits_op),
    .fromCSR_wdata_bits_data                      (fromCSR2_wdata_bits_data),
    .fromCSR_claims_0                             (fromCSR2_claims_0),
    .fromCSR_claims_1                             (fromCSR2_claims_1),
    .fromCSR_claims_2                             (fromCSR2_claims_2),
    .soc_clock                                    (clock),
    .soc_reset                                    (reset)
  );
  AXI4Map_6 axi4map_3 (
    .auto_in_aw_valid       (_imsics_fromMem_xbar_auto_out_3_aw_valid),
    .auto_in_aw_bits_id     (_imsics_fromMem_xbar_auto_out_3_aw_bits_id),
    .auto_in_aw_bits_addr   (_imsics_fromMem_xbar_auto_out_3_aw_bits_addr),
    .auto_in_aw_bits_len    (_imsics_fromMem_xbar_auto_out_3_aw_bits_len),
    .auto_in_aw_bits_size   (_imsics_fromMem_xbar_auto_out_3_aw_bits_size),
    .auto_in_aw_bits_burst  (_imsics_fromMem_xbar_auto_out_3_aw_bits_burst),
    .auto_in_aw_bits_lock   (_imsics_fromMem_xbar_auto_out_3_aw_bits_lock),
    .auto_in_aw_bits_cache  (_imsics_fromMem_xbar_auto_out_3_aw_bits_cache),
    .auto_in_aw_bits_prot   (_imsics_fromMem_xbar_auto_out_3_aw_bits_prot),
    .auto_in_aw_bits_qos    (_imsics_fromMem_xbar_auto_out_3_aw_bits_qos),
    .auto_in_w_valid        (_imsics_fromMem_xbar_auto_out_3_w_valid),
    .auto_in_w_bits_data    (_imsics_fromMem_xbar_auto_out_3_w_bits_data),
    .auto_in_w_bits_strb    (_imsics_fromMem_xbar_auto_out_3_w_bits_strb),
    .auto_in_w_bits_last    (_imsics_fromMem_xbar_auto_out_3_w_bits_last),
    .auto_in_b_ready        (_imsics_fromMem_xbar_auto_out_3_b_ready),
    .auto_in_b_valid        (_axi4map_3_auto_in_b_valid),
    .auto_in_b_bits_id      (_axi4map_3_auto_in_b_bits_id),
    .auto_in_b_bits_resp    (_axi4map_3_auto_in_b_bits_resp),
    .auto_in_ar_ready       (_axi4map_3_auto_in_ar_ready),
    .auto_in_ar_valid       (_imsics_fromMem_xbar_auto_out_3_ar_valid),
    .auto_in_ar_bits_id     (_imsics_fromMem_xbar_auto_out_3_ar_bits_id),
    .auto_in_ar_bits_addr   (_imsics_fromMem_xbar_auto_out_3_ar_bits_addr),
    .auto_in_ar_bits_len    (_imsics_fromMem_xbar_auto_out_3_ar_bits_len),
    .auto_in_ar_bits_size   (_imsics_fromMem_xbar_auto_out_3_ar_bits_size),
    .auto_in_ar_bits_burst  (_imsics_fromMem_xbar_auto_out_3_ar_bits_burst),
    .auto_in_ar_bits_lock   (_imsics_fromMem_xbar_auto_out_3_ar_bits_lock),
    .auto_in_ar_bits_cache  (_imsics_fromMem_xbar_auto_out_3_ar_bits_cache),
    .auto_in_ar_bits_prot   (_imsics_fromMem_xbar_auto_out_3_ar_bits_prot),
    .auto_in_ar_bits_qos    (_imsics_fromMem_xbar_auto_out_3_ar_bits_qos),
    .auto_in_r_ready        (_imsics_fromMem_xbar_auto_out_3_r_ready),
    .auto_in_r_valid        (_axi4map_3_auto_in_r_valid),
    .auto_in_r_bits_id      (_axi4map_3_auto_in_r_bits_id),
    .auto_in_r_bits_data    (_axi4map_3_auto_in_r_bits_data),
    .auto_in_r_bits_resp    (_axi4map_3_auto_in_r_bits_resp),
    .auto_in_r_bits_last    (_axi4map_3_auto_in_r_bits_last),
    .auto_out_aw_valid      (_axi4map_3_auto_out_aw_valid),
    .auto_out_aw_bits_id    (_axi4map_3_auto_out_aw_bits_id),
    .auto_out_aw_bits_addr  (_axi4map_3_auto_out_aw_bits_addr),
    .auto_out_aw_bits_len   (_axi4map_3_auto_out_aw_bits_len),
    .auto_out_aw_bits_size  (_axi4map_3_auto_out_aw_bits_size),
    .auto_out_aw_bits_burst (_axi4map_3_auto_out_aw_bits_burst),
    .auto_out_aw_bits_lock  (_axi4map_3_auto_out_aw_bits_lock),
    .auto_out_aw_bits_cache (_axi4map_3_auto_out_aw_bits_cache),
    .auto_out_aw_bits_prot  (_axi4map_3_auto_out_aw_bits_prot),
    .auto_out_aw_bits_qos   (_axi4map_3_auto_out_aw_bits_qos),
    .auto_out_w_valid       (_axi4map_3_auto_out_w_valid),
    .auto_out_w_bits_data   (_axi4map_3_auto_out_w_bits_data),
    .auto_out_w_bits_strb   (_axi4map_3_auto_out_w_bits_strb),
    .auto_out_w_bits_last   (_axi4map_3_auto_out_w_bits_last),
    .auto_out_b_ready       (_axi4map_3_auto_out_b_ready),
    .auto_out_b_valid       (_imsic_3_auto_axireg_axireg_axi4xbar_in_b_valid),
    .auto_out_b_bits_id     (_imsic_3_auto_axireg_axireg_axi4xbar_in_b_bits_id),
    .auto_out_b_bits_resp   (_imsic_3_auto_axireg_axireg_axi4xbar_in_b_bits_resp),
    .auto_out_ar_ready      (_imsic_3_auto_axireg_axireg_axi4xbar_in_ar_ready),
    .auto_out_ar_valid      (_axi4map_3_auto_out_ar_valid),
    .auto_out_ar_bits_id    (_axi4map_3_auto_out_ar_bits_id),
    .auto_out_ar_bits_addr  (_axi4map_3_auto_out_ar_bits_addr),
    .auto_out_ar_bits_len   (_axi4map_3_auto_out_ar_bits_len),
    .auto_out_ar_bits_size  (_axi4map_3_auto_out_ar_bits_size),
    .auto_out_ar_bits_burst (_axi4map_3_auto_out_ar_bits_burst),
    .auto_out_ar_bits_lock  (_axi4map_3_auto_out_ar_bits_lock),
    .auto_out_ar_bits_cache (_axi4map_3_auto_out_ar_bits_cache),
    .auto_out_ar_bits_prot  (_axi4map_3_auto_out_ar_bits_prot),
    .auto_out_ar_bits_qos   (_axi4map_3_auto_out_ar_bits_qos),
    .auto_out_r_ready       (_axi4map_3_auto_out_r_ready),
    .auto_out_r_valid       (_imsic_3_auto_axireg_axireg_axi4xbar_in_r_valid),
    .auto_out_r_bits_id     (_imsic_3_auto_axireg_axireg_axi4xbar_in_r_bits_id),
    .auto_out_r_bits_data   (_imsic_3_auto_axireg_axireg_axi4xbar_in_r_bits_data),
    .auto_out_r_bits_resp   (_imsic_3_auto_axireg_axireg_axi4xbar_in_r_bits_resp),
    .auto_out_r_bits_last   (_imsic_3_auto_axireg_axireg_axi4xbar_in_r_bits_last)
  );
  AXI4IMSIC imsic_3 (
    .clock                                        (clock),
    .reset                                        (reset),
    .auto_axireg_axireg_axi4xbar_in_aw_valid      (_axi4map_3_auto_out_aw_valid),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_id    (_axi4map_3_auto_out_aw_bits_id),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_addr  (_axi4map_3_auto_out_aw_bits_addr),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_len   (_axi4map_3_auto_out_aw_bits_len),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_size  (_axi4map_3_auto_out_aw_bits_size),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_burst (_axi4map_3_auto_out_aw_bits_burst),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_lock  (_axi4map_3_auto_out_aw_bits_lock),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_cache (_axi4map_3_auto_out_aw_bits_cache),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_prot  (_axi4map_3_auto_out_aw_bits_prot),
    .auto_axireg_axireg_axi4xbar_in_aw_bits_qos   (_axi4map_3_auto_out_aw_bits_qos),
    .auto_axireg_axireg_axi4xbar_in_w_valid       (_axi4map_3_auto_out_w_valid),
    .auto_axireg_axireg_axi4xbar_in_w_bits_data   (_axi4map_3_auto_out_w_bits_data),
    .auto_axireg_axireg_axi4xbar_in_w_bits_strb   (_axi4map_3_auto_out_w_bits_strb),
    .auto_axireg_axireg_axi4xbar_in_w_bits_last   (_axi4map_3_auto_out_w_bits_last),
    .auto_axireg_axireg_axi4xbar_in_b_ready       (_axi4map_3_auto_out_b_ready),
    .auto_axireg_axireg_axi4xbar_in_b_valid
      (_imsic_3_auto_axireg_axireg_axi4xbar_in_b_valid),
    .auto_axireg_axireg_axi4xbar_in_b_bits_id
      (_imsic_3_auto_axireg_axireg_axi4xbar_in_b_bits_id),
    .auto_axireg_axireg_axi4xbar_in_b_bits_resp
      (_imsic_3_auto_axireg_axireg_axi4xbar_in_b_bits_resp),
    .auto_axireg_axireg_axi4xbar_in_ar_ready
      (_imsic_3_auto_axireg_axireg_axi4xbar_in_ar_ready),
    .auto_axireg_axireg_axi4xbar_in_ar_valid      (_axi4map_3_auto_out_ar_valid),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_id    (_axi4map_3_auto_out_ar_bits_id),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_addr  (_axi4map_3_auto_out_ar_bits_addr),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_len   (_axi4map_3_auto_out_ar_bits_len),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_size  (_axi4map_3_auto_out_ar_bits_size),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_burst (_axi4map_3_auto_out_ar_bits_burst),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_lock  (_axi4map_3_auto_out_ar_bits_lock),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_cache (_axi4map_3_auto_out_ar_bits_cache),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_prot  (_axi4map_3_auto_out_ar_bits_prot),
    .auto_axireg_axireg_axi4xbar_in_ar_bits_qos   (_axi4map_3_auto_out_ar_bits_qos),
    .auto_axireg_axireg_axi4xbar_in_r_ready       (_axi4map_3_auto_out_r_ready),
    .auto_axireg_axireg_axi4xbar_in_r_valid
      (_imsic_3_auto_axireg_axireg_axi4xbar_in_r_valid),
    .auto_axireg_axireg_axi4xbar_in_r_bits_id
      (_imsic_3_auto_axireg_axireg_axi4xbar_in_r_bits_id),
    .auto_axireg_axireg_axi4xbar_in_r_bits_data
      (_imsic_3_auto_axireg_axireg_axi4xbar_in_r_bits_data),
    .auto_axireg_axireg_axi4xbar_in_r_bits_resp
      (_imsic_3_auto_axireg_axireg_axi4xbar_in_r_bits_resp),
    .auto_axireg_axireg_axi4xbar_in_r_bits_last
      (_imsic_3_auto_axireg_axireg_axi4xbar_in_r_bits_last),
    .toCSR_rdata_valid                            (toCSR3_rdata_valid),
    .toCSR_rdata_bits                             (toCSR3_rdata_bits),
    .toCSR_illegal                                (toCSR3_illegal),
    .toCSR_pendings                               (toCSR3_pendings),
    .toCSR_topeis_0                               (toCSR3_topeis_0),
    .toCSR_topeis_1                               (toCSR3_topeis_1),
    .toCSR_topeis_2                               (toCSR3_topeis_2),
    .fromCSR_addr_valid                           (fromCSR3_addr_valid),
    .fromCSR_addr_bits                            (fromCSR3_addr_bits),
    .fromCSR_virt                                 (fromCSR3_virt),
    .fromCSR_priv                                 (fromCSR3_priv),
    .fromCSR_vgein                                (fromCSR3_vgein),
    .fromCSR_wdata_valid                          (fromCSR3_wdata_valid),
    .fromCSR_wdata_bits_op                        (fromCSR3_wdata_bits_op),
    .fromCSR_wdata_bits_data                      (fromCSR3_wdata_bits_data),
    .fromCSR_claims_0                             (fromCSR3_claims_0),
    .fromCSR_claims_1                             (fromCSR3_claims_1),
    .fromCSR_claims_2                             (fromCSR3_claims_2),
    .soc_clock                                    (clock),
    .soc_reset                                    (reset)
  );
  AXI4APLIC aplic (
    .clock                         (clock),
    .reset                         (reset),
    .auto_toIMSIC_out_aw_valid     (_aplic_auto_toIMSIC_out_aw_valid),
    .auto_toIMSIC_out_aw_bits_id   (_aplic_auto_toIMSIC_out_aw_bits_id),
    .auto_toIMSIC_out_aw_bits_addr (_aplic_auto_toIMSIC_out_aw_bits_addr),
    .auto_toIMSIC_out_aw_bits_size (_aplic_auto_toIMSIC_out_aw_bits_size),
    .auto_toIMSIC_out_w_valid      (_aplic_auto_toIMSIC_out_w_valid),
    .auto_toIMSIC_out_w_bits_data  (_aplic_auto_toIMSIC_out_w_bits_data),
    .auto_toIMSIC_out_w_bits_strb  (_aplic_auto_toIMSIC_out_w_bits_strb),
    .auto_toIMSIC_out_w_bits_last  (_aplic_auto_toIMSIC_out_w_bits_last),
    .auto_toIMSIC_out_b_ready      (_aplic_auto_toIMSIC_out_b_ready),
    .auto_toIMSIC_out_b_valid      (_imsics_fromMem_xbar_auto_in_1_b_valid),
    .auto_toIMSIC_out_b_bits_id    (_imsics_fromMem_xbar_auto_in_1_b_bits_id),
    .auto_toIMSIC_out_r_valid      (_imsics_fromMem_xbar_auto_in_1_r_valid),
    .auto_toIMSIC_out_r_bits_id    (_imsics_fromMem_xbar_auto_in_1_r_bits_id),
    .auto_fromCPU_in_aw_ready      (_aplic_auto_fromCPU_in_aw_ready),
    .auto_fromCPU_in_aw_valid      (_toAIA_xbar_auto_out_1_aw_valid),
    .auto_fromCPU_in_aw_bits_id    (_toAIA_xbar_auto_out_1_aw_bits_id),
    .auto_fromCPU_in_aw_bits_addr  (_toAIA_xbar_auto_out_1_aw_bits_addr),
    .auto_fromCPU_in_aw_bits_len   (_toAIA_xbar_auto_out_1_aw_bits_len),
    .auto_fromCPU_in_aw_bits_size  (_toAIA_xbar_auto_out_1_aw_bits_size),
    .auto_fromCPU_in_aw_bits_burst (_toAIA_xbar_auto_out_1_aw_bits_burst),
    .auto_fromCPU_in_aw_bits_lock  (_toAIA_xbar_auto_out_1_aw_bits_lock),
    .auto_fromCPU_in_aw_bits_cache (_toAIA_xbar_auto_out_1_aw_bits_cache),
    .auto_fromCPU_in_aw_bits_prot  (_toAIA_xbar_auto_out_1_aw_bits_prot),
    .auto_fromCPU_in_aw_bits_qos   (_toAIA_xbar_auto_out_1_aw_bits_qos),
    .auto_fromCPU_in_w_ready       (_aplic_auto_fromCPU_in_w_ready),
    .auto_fromCPU_in_w_valid       (_toAIA_xbar_auto_out_1_w_valid),
    .auto_fromCPU_in_w_bits_data   (_toAIA_xbar_auto_out_1_w_bits_data),
    .auto_fromCPU_in_w_bits_strb   (_toAIA_xbar_auto_out_1_w_bits_strb),
    .auto_fromCPU_in_w_bits_last   (_toAIA_xbar_auto_out_1_w_bits_last),
    .auto_fromCPU_in_b_ready       (_toAIA_xbar_auto_out_1_b_ready),
    .auto_fromCPU_in_b_valid       (_aplic_auto_fromCPU_in_b_valid),
    .auto_fromCPU_in_b_bits_id     (_aplic_auto_fromCPU_in_b_bits_id),
    .auto_fromCPU_in_b_bits_resp   (_aplic_auto_fromCPU_in_b_bits_resp),
    .auto_fromCPU_in_ar_ready      (_aplic_auto_fromCPU_in_ar_ready),
    .auto_fromCPU_in_ar_valid      (_toAIA_xbar_auto_out_1_ar_valid),
    .auto_fromCPU_in_ar_bits_id    (_toAIA_xbar_auto_out_1_ar_bits_id),
    .auto_fromCPU_in_ar_bits_addr  (_toAIA_xbar_auto_out_1_ar_bits_addr),
    .auto_fromCPU_in_ar_bits_len   (_toAIA_xbar_auto_out_1_ar_bits_len),
    .auto_fromCPU_in_ar_bits_size  (_toAIA_xbar_auto_out_1_ar_bits_size),
    .auto_fromCPU_in_ar_bits_burst (_toAIA_xbar_auto_out_1_ar_bits_burst),
    .auto_fromCPU_in_ar_bits_lock  (_toAIA_xbar_auto_out_1_ar_bits_lock),
    .auto_fromCPU_in_ar_bits_cache (_toAIA_xbar_auto_out_1_ar_bits_cache),
    .auto_fromCPU_in_ar_bits_prot  (_toAIA_xbar_auto_out_1_ar_bits_prot),
    .auto_fromCPU_in_ar_bits_qos   (_toAIA_xbar_auto_out_1_ar_bits_qos),
    .auto_fromCPU_in_r_ready       (_toAIA_xbar_auto_out_1_r_ready),
    .auto_fromCPU_in_r_valid       (_aplic_auto_fromCPU_in_r_valid),
    .auto_fromCPU_in_r_bits_id     (_aplic_auto_fromCPU_in_r_bits_id),
    .auto_fromCPU_in_r_bits_data   (_aplic_auto_fromCPU_in_r_bits_data),
    .auto_fromCPU_in_r_bits_resp   (_aplic_auto_fromCPU_in_r_bits_resp),
    .auto_fromCPU_in_r_bits_last   (_aplic_auto_fromCPU_in_r_bits_last),
    .intSrcs_1                     (intSrcs_1),
    .intSrcs_2                     (intSrcs_2),
    .intSrcs_3                     (intSrcs_3),
    .intSrcs_4                     (intSrcs_4),
    .intSrcs_5                     (intSrcs_5),
    .intSrcs_6                     (intSrcs_6),
    .intSrcs_7                     (intSrcs_7),
    .intSrcs_8                     (intSrcs_8),
    .intSrcs_9                     (intSrcs_9),
    .intSrcs_10                    (intSrcs_10),
    .intSrcs_11                    (intSrcs_11),
    .intSrcs_12                    (intSrcs_12),
    .intSrcs_13                    (intSrcs_13),
    .intSrcs_14                    (intSrcs_14),
    .intSrcs_15                    (intSrcs_15),
    .intSrcs_16                    (intSrcs_16),
    .intSrcs_17                    (intSrcs_17),
    .intSrcs_18                    (intSrcs_18),
    .intSrcs_19                    (intSrcs_19),
    .intSrcs_20                    (intSrcs_20),
    .intSrcs_21                    (intSrcs_21),
    .intSrcs_22                    (intSrcs_22),
    .intSrcs_23                    (intSrcs_23),
    .intSrcs_24                    (intSrcs_24),
    .intSrcs_25                    (intSrcs_25),
    .intSrcs_26                    (intSrcs_26),
    .intSrcs_27                    (intSrcs_27),
    .intSrcs_28                    (intSrcs_28),
    .intSrcs_29                    (intSrcs_29),
    .intSrcs_30                    (intSrcs_30),
    .intSrcs_31                    (intSrcs_31),
    .intSrcs_32                    (intSrcs_32),
    .intSrcs_33                    (intSrcs_33),
    .intSrcs_34                    (intSrcs_34),
    .intSrcs_35                    (intSrcs_35),
    .intSrcs_36                    (intSrcs_36),
    .intSrcs_37                    (intSrcs_37),
    .intSrcs_38                    (intSrcs_38),
    .intSrcs_39                    (intSrcs_39),
    .intSrcs_40                    (intSrcs_40),
    .intSrcs_41                    (intSrcs_41),
    .intSrcs_42                    (intSrcs_42),
    .intSrcs_43                    (intSrcs_43),
    .intSrcs_44                    (intSrcs_44),
    .intSrcs_45                    (intSrcs_45),
    .intSrcs_46                    (intSrcs_46),
    .intSrcs_47                    (intSrcs_47),
    .intSrcs_48                    (intSrcs_48),
    .intSrcs_49                    (intSrcs_49),
    .intSrcs_50                    (intSrcs_50),
    .intSrcs_51                    (intSrcs_51),
    .intSrcs_52                    (intSrcs_52),
    .intSrcs_53                    (intSrcs_53),
    .intSrcs_54                    (intSrcs_54),
    .intSrcs_55                    (intSrcs_55),
    .intSrcs_56                    (intSrcs_56),
    .intSrcs_57                    (intSrcs_57),
    .intSrcs_58                    (intSrcs_58),
    .intSrcs_59                    (intSrcs_59),
    .intSrcs_60                    (intSrcs_60),
    .intSrcs_61                    (intSrcs_61),
    .intSrcs_62                    (intSrcs_62),
    .intSrcs_63                    (intSrcs_63),
    .intSrcs_64                    (intSrcs_64),
    .intSrcs_65                    (intSrcs_65),
    .intSrcs_66                    (intSrcs_66),
    .intSrcs_67                    (intSrcs_67),
    .intSrcs_68                    (intSrcs_68),
    .intSrcs_69                    (intSrcs_69),
    .intSrcs_70                    (intSrcs_70),
    .intSrcs_71                    (intSrcs_71),
    .intSrcs_72                    (intSrcs_72),
    .intSrcs_73                    (intSrcs_73),
    .intSrcs_74                    (intSrcs_74),
    .intSrcs_75                    (intSrcs_75),
    .intSrcs_76                    (intSrcs_76),
    .intSrcs_77                    (intSrcs_77),
    .intSrcs_78                    (intSrcs_78),
    .intSrcs_79                    (intSrcs_79),
    .intSrcs_80                    (intSrcs_80),
    .intSrcs_81                    (intSrcs_81),
    .intSrcs_82                    (intSrcs_82),
    .intSrcs_83                    (intSrcs_83),
    .intSrcs_84                    (intSrcs_84),
    .intSrcs_85                    (intSrcs_85),
    .intSrcs_86                    (intSrcs_86),
    .intSrcs_87                    (intSrcs_87),
    .intSrcs_88                    (intSrcs_88),
    .intSrcs_89                    (intSrcs_89),
    .intSrcs_90                    (intSrcs_90),
    .intSrcs_91                    (intSrcs_91),
    .intSrcs_92                    (intSrcs_92),
    .intSrcs_93                    (intSrcs_93),
    .intSrcs_94                    (intSrcs_94),
    .intSrcs_95                    (intSrcs_95),
    .intSrcs_96                    (intSrcs_96),
    .intSrcs_97                    (intSrcs_97),
    .intSrcs_98                    (intSrcs_98),
    .intSrcs_99                    (intSrcs_99),
    .intSrcs_100                   (intSrcs_100),
    .intSrcs_101                   (intSrcs_101),
    .intSrcs_102                   (intSrcs_102),
    .intSrcs_103                   (intSrcs_103),
    .intSrcs_104                   (intSrcs_104),
    .intSrcs_105                   (intSrcs_105),
    .intSrcs_106                   (intSrcs_106),
    .intSrcs_107                   (intSrcs_107),
    .intSrcs_108                   (intSrcs_108),
    .intSrcs_109                   (intSrcs_109),
    .intSrcs_110                   (intSrcs_110),
    .intSrcs_111                   (intSrcs_111),
    .intSrcs_112                   (intSrcs_112),
    .intSrcs_113                   (intSrcs_113),
    .intSrcs_114                   (intSrcs_114),
    .intSrcs_115                   (intSrcs_115),
    .intSrcs_116                   (intSrcs_116),
    .intSrcs_117                   (intSrcs_117),
    .intSrcs_118                   (intSrcs_118),
    .intSrcs_119                   (intSrcs_119),
    .intSrcs_120                   (intSrcs_120),
    .intSrcs_121                   (intSrcs_121),
    .intSrcs_122                   (intSrcs_122),
    .intSrcs_123                   (intSrcs_123),
    .intSrcs_124                   (intSrcs_124),
    .intSrcs_125                   (intSrcs_125),
    .intSrcs_126                   (intSrcs_126),
    .intSrcs_127                   (intSrcs_127)
  );
endmodule

