// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module AXI4APLIC(
  input         clock,
  input         reset,
  output        auto_toIMSIC_out_aw_valid,
  output [4:0]  auto_toIMSIC_out_aw_bits_id,
  output [31:0] auto_toIMSIC_out_aw_bits_addr,
  output [2:0]  auto_toIMSIC_out_aw_bits_size,
  output        auto_toIMSIC_out_w_valid,
  output [31:0] auto_toIMSIC_out_w_bits_data,
  output [3:0]  auto_toIMSIC_out_w_bits_strb,
  output        auto_toIMSIC_out_w_bits_last,
  output        auto_toIMSIC_out_b_ready,
  input         auto_toIMSIC_out_b_valid,
  input  [4:0]  auto_toIMSIC_out_b_bits_id,
  input         auto_toIMSIC_out_r_valid,
  input  [4:0]  auto_toIMSIC_out_r_bits_id,
  output        auto_fromCPU_in_aw_ready,
  input         auto_fromCPU_in_aw_valid,
  input  [3:0]  auto_fromCPU_in_aw_bits_id,
  input  [28:0] auto_fromCPU_in_aw_bits_addr,
  input  [7:0]  auto_fromCPU_in_aw_bits_len,
  input  [2:0]  auto_fromCPU_in_aw_bits_size,
  input  [1:0]  auto_fromCPU_in_aw_bits_burst,
  input         auto_fromCPU_in_aw_bits_lock,
  input  [3:0]  auto_fromCPU_in_aw_bits_cache,
  input  [2:0]  auto_fromCPU_in_aw_bits_prot,
  input  [3:0]  auto_fromCPU_in_aw_bits_qos,
  output        auto_fromCPU_in_w_ready,
  input         auto_fromCPU_in_w_valid,
  input  [31:0] auto_fromCPU_in_w_bits_data,
  input  [3:0]  auto_fromCPU_in_w_bits_strb,
  input         auto_fromCPU_in_w_bits_last,
  input         auto_fromCPU_in_b_ready,
  output        auto_fromCPU_in_b_valid,
  output [3:0]  auto_fromCPU_in_b_bits_id,
  output [1:0]  auto_fromCPU_in_b_bits_resp,
  output        auto_fromCPU_in_ar_ready,
  input         auto_fromCPU_in_ar_valid,
  input  [3:0]  auto_fromCPU_in_ar_bits_id,
  input  [28:0] auto_fromCPU_in_ar_bits_addr,
  input  [7:0]  auto_fromCPU_in_ar_bits_len,
  input  [2:0]  auto_fromCPU_in_ar_bits_size,
  input  [1:0]  auto_fromCPU_in_ar_bits_burst,
  input         auto_fromCPU_in_ar_bits_lock,
  input  [3:0]  auto_fromCPU_in_ar_bits_cache,
  input  [2:0]  auto_fromCPU_in_ar_bits_prot,
  input  [3:0]  auto_fromCPU_in_ar_bits_qos,
  input         auto_fromCPU_in_r_ready,
  output        auto_fromCPU_in_r_valid,
  output [3:0]  auto_fromCPU_in_r_bits_id,
  output [31:0] auto_fromCPU_in_r_bits_data,
  output [1:0]  auto_fromCPU_in_r_bits_resp,
  output        auto_fromCPU_in_r_bits_last,
  input         intSrcs_1,
  input         intSrcs_2,
  input         intSrcs_3,
  input         intSrcs_4,
  input         intSrcs_5,
  input         intSrcs_6,
  input         intSrcs_7,
  input         intSrcs_8,
  input         intSrcs_9,
  input         intSrcs_10,
  input         intSrcs_11,
  input         intSrcs_12,
  input         intSrcs_13,
  input         intSrcs_14,
  input         intSrcs_15,
  input         intSrcs_16,
  input         intSrcs_17,
  input         intSrcs_18,
  input         intSrcs_19,
  input         intSrcs_20,
  input         intSrcs_21,
  input         intSrcs_22,
  input         intSrcs_23,
  input         intSrcs_24,
  input         intSrcs_25,
  input         intSrcs_26,
  input         intSrcs_27,
  input         intSrcs_28,
  input         intSrcs_29,
  input         intSrcs_30,
  input         intSrcs_31,
  input         intSrcs_32,
  input         intSrcs_33,
  input         intSrcs_34,
  input         intSrcs_35,
  input         intSrcs_36,
  input         intSrcs_37,
  input         intSrcs_38,
  input         intSrcs_39,
  input         intSrcs_40,
  input         intSrcs_41,
  input         intSrcs_42,
  input         intSrcs_43,
  input         intSrcs_44,
  input         intSrcs_45,
  input         intSrcs_46,
  input         intSrcs_47,
  input         intSrcs_48,
  input         intSrcs_49,
  input         intSrcs_50,
  input         intSrcs_51,
  input         intSrcs_52,
  input         intSrcs_53,
  input         intSrcs_54,
  input         intSrcs_55,
  input         intSrcs_56,
  input         intSrcs_57,
  input         intSrcs_58,
  input         intSrcs_59,
  input         intSrcs_60,
  input         intSrcs_61,
  input         intSrcs_62,
  input         intSrcs_63,
  input         intSrcs_64,
  input         intSrcs_65,
  input         intSrcs_66,
  input         intSrcs_67,
  input         intSrcs_68,
  input         intSrcs_69,
  input         intSrcs_70,
  input         intSrcs_71,
  input         intSrcs_72,
  input         intSrcs_73,
  input         intSrcs_74,
  input         intSrcs_75,
  input         intSrcs_76,
  input         intSrcs_77,
  input         intSrcs_78,
  input         intSrcs_79,
  input         intSrcs_80,
  input         intSrcs_81,
  input         intSrcs_82,
  input         intSrcs_83,
  input         intSrcs_84,
  input         intSrcs_85,
  input         intSrcs_86,
  input         intSrcs_87,
  input         intSrcs_88,
  input         intSrcs_89,
  input         intSrcs_90,
  input         intSrcs_91,
  input         intSrcs_92,
  input         intSrcs_93,
  input         intSrcs_94,
  input         intSrcs_95,
  input         intSrcs_96,
  input         intSrcs_97,
  input         intSrcs_98,
  input         intSrcs_99,
  input         intSrcs_100,
  input         intSrcs_101,
  input         intSrcs_102,
  input         intSrcs_103,
  input         intSrcs_104,
  input         intSrcs_105,
  input         intSrcs_106,
  input         intSrcs_107,
  input         intSrcs_108,
  input         intSrcs_109,
  input         intSrcs_110,
  input         intSrcs_111,
  input         intSrcs_112,
  input         intSrcs_113,
  input         intSrcs_114,
  input         intSrcs_115,
  input         intSrcs_116,
  input         intSrcs_117,
  input         intSrcs_118,
  input         intSrcs_119,
  input         intSrcs_120,
  input         intSrcs_121,
  input         intSrcs_122,
  input         intSrcs_123,
  input         intSrcs_124,
  input         intSrcs_125,
  input         intSrcs_126,
  input         intSrcs_127
);

  wire [3:0]  domainFromCPUIn_1_ar_bits_qos;
  wire [2:0]  domainFromCPUIn_1_ar_bits_prot;
  wire [3:0]  domainFromCPUIn_1_ar_bits_cache;
  wire        domainFromCPUIn_1_ar_bits_lock;
  wire [1:0]  domainFromCPUIn_1_ar_bits_burst;
  wire [7:0]  domainFromCPUIn_1_ar_bits_len;
  wire        domainFromCPUIn_1_w_bits_last;
  wire [31:0] domainFromCPUIn_1_w_bits_data;
  wire [3:0]  domainFromCPUIn_1_aw_bits_qos;
  wire [2:0]  domainFromCPUIn_1_aw_bits_prot;
  wire [3:0]  domainFromCPUIn_1_aw_bits_cache;
  wire        domainFromCPUIn_1_aw_bits_lock;
  wire [1:0]  domainFromCPUIn_1_aw_bits_burst;
  wire [2:0]  domainFromCPUIn_1_aw_bits_size;
  wire [7:0]  domainFromCPUIn_1_aw_bits_len;
  wire [3:0]  domainFromCPUIn_ar_bits_qos;
  wire [2:0]  domainFromCPUIn_ar_bits_prot;
  wire [3:0]  domainFromCPUIn_ar_bits_cache;
  wire        domainFromCPUIn_ar_bits_lock;
  wire [1:0]  domainFromCPUIn_ar_bits_burst;
  wire [7:0]  domainFromCPUIn_ar_bits_len;
  wire        domainFromCPUIn_w_bits_last;
  wire [31:0] domainFromCPUIn_w_bits_data;
  wire [3:0]  domainFromCPUIn_aw_bits_qos;
  wire [2:0]  domainFromCPUIn_aw_bits_prot;
  wire [3:0]  domainFromCPUIn_aw_bits_cache;
  wire        domainFromCPUIn_aw_bits_lock;
  wire [1:0]  domainFromCPUIn_aw_bits_burst;
  wire [2:0]  domainFromCPUIn_aw_bits_size;
  wire [7:0]  domainFromCPUIn_aw_bits_len;
  wire        _aplic_ios_0_msi_valid;
  wire [63:0] _aplic_ios_0_msi_bits_addr;
  wire [31:0] _aplic_ios_0_msi_bits_data;
  wire        _aplic_ios_0_regmapIn_ready;
  wire        _aplic_ios_0_regmapOut_valid;
  wire        _aplic_ios_0_regmapOut_bits_read;
  wire        _aplic_ios_1_msi_valid;
  wire [63:0] _aplic_ios_1_msi_bits_addr;
  wire [31:0] _aplic_ios_1_msi_bits_data;
  wire        _aplic_ios_1_regmapIn_ready;
  wire        _aplic_ios_1_regmapOut_valid;
  wire        _aplic_ios_1_regmapOut_bits_read;
  wire        _toIMSIC_auto_in_1_b_valid;
  wire        _toIMSIC_auto_in_0_b_valid;
  wire        _fromCPU_auto_out_1_aw_valid;
  wire        _fromCPU_auto_out_1_w_valid;
  wire        _fromCPU_auto_out_1_b_ready;
  wire        _fromCPU_auto_out_1_ar_valid;
  wire        _fromCPU_auto_out_1_r_ready;
  wire        _fromCPU_auto_out_0_aw_valid;
  wire        _fromCPU_auto_out_0_w_valid;
  wire        _fromCPU_auto_out_0_b_ready;
  wire        _fromCPU_auto_out_0_ar_valid;
  wire        _fromCPU_auto_out_0_r_ready;
  wire [1:0]  domainFromCPUIn_b_bits_resp = 2'h0;
  wire [1:0]  domainFromCPUIn_r_bits_resp = 2'h0;
  wire [1:0]  domainFromCPUIn_1_b_bits_resp = 2'h0;
  wire [1:0]  domainFromCPUIn_1_r_bits_resp = 2'h0;
  wire        domainFromCPUIn_r_bits_last = 1'h1;
  wire        domainFromCPUIn_1_r_bits_last = 1'h1;
  reg  [3:0]  arIdReg;
  wire [3:0]  domainFromCPUIn_r_bits_id = arIdReg;
  reg  [3:0]  awIdReg;
  wire [3:0]  domainFromCPUIn_b_bits_id = awIdReg;
  wire [28:0] domainFromCPUIn_ar_bits_addr;
  wire [28:0] domainFromCPUIn_aw_bits_addr;
  wire [2:0]  domainFromCPUIn_ar_bits_size;
  wire        mask_sub_0_1 =
    (|(domainFromCPUIn_ar_bits_size[2:1])) | domainFromCPUIn_ar_bits_size[0]
    & ~(domainFromCPUIn_ar_bits_addr[1]);
  wire        mask_sub_1_1 =
    (|(domainFromCPUIn_ar_bits_size[2:1])) | domainFromCPUIn_ar_bits_size[0]
    & domainFromCPUIn_ar_bits_addr[1];
  wire [3:0]  domainFromCPUIn_w_bits_strb;
  reg  [3:0]  arIdReg_1;
  wire [3:0]  domainFromCPUIn_1_r_bits_id = arIdReg_1;
  reg  [3:0]  awIdReg_1;
  wire [3:0]  domainFromCPUIn_1_b_bits_id = awIdReg_1;
  wire [28:0] domainFromCPUIn_1_ar_bits_addr;
  wire [28:0] domainFromCPUIn_1_aw_bits_addr;
  wire [2:0]  domainFromCPUIn_1_ar_bits_size;
  wire        mask_sub_0_1_1 =
    (|(domainFromCPUIn_1_ar_bits_size[2:1])) | domainFromCPUIn_1_ar_bits_size[0]
    & ~(domainFromCPUIn_1_ar_bits_addr[1]);
  wire        mask_sub_1_1_1 =
    (|(domainFromCPUIn_1_ar_bits_size[2:1])) | domainFromCPUIn_1_ar_bits_size[0]
    & domainFromCPUIn_1_ar_bits_addr[1];
  wire [3:0]  domainFromCPUIn_1_w_bits_strb;
  wire [3:0]  domainFromCPUIn_aw_bits_id;
  wire [3:0]  domainFromCPUIn_ar_bits_id;
  wire [3:0]  domainFromCPUIn_1_aw_bits_id;
  wire [3:0]  domainFromCPUIn_1_ar_bits_id;
  always @(posedge clock) begin
    if (reset) begin
      arIdReg <= 4'h0;
      awIdReg <= 4'h0;
      arIdReg_1 <= 4'h0;
      awIdReg_1 <= 4'h0;
    end
    else begin
      if (_fromCPU_auto_out_0_ar_valid)
        arIdReg <= domainFromCPUIn_ar_bits_id;
      if (_fromCPU_auto_out_0_aw_valid)
        awIdReg <= domainFromCPUIn_aw_bits_id;
      if (_fromCPU_auto_out_1_ar_valid)
        arIdReg_1 <= domainFromCPUIn_1_ar_bits_id;
      if (_fromCPU_auto_out_1_aw_valid)
        awIdReg_1 <= domainFromCPUIn_1_aw_bits_id;
    end
  end // always @(posedge)
  wire [31:0] domainFromCPUIn_r_bits_data;
  wire [31:0] domainFromCPUIn_1_r_bits_data;
  AXI4Xbar_6 fromCPU (
    .clock                    (clock),
    .reset                    (reset),
    .auto_in_aw_ready         (auto_fromCPU_in_aw_ready),
    .auto_in_aw_valid         (auto_fromCPU_in_aw_valid),
    .auto_in_aw_bits_id       (auto_fromCPU_in_aw_bits_id),
    .auto_in_aw_bits_addr     (auto_fromCPU_in_aw_bits_addr),
    .auto_in_aw_bits_len      (auto_fromCPU_in_aw_bits_len),
    .auto_in_aw_bits_size     (auto_fromCPU_in_aw_bits_size),
    .auto_in_aw_bits_burst    (auto_fromCPU_in_aw_bits_burst),
    .auto_in_aw_bits_lock     (auto_fromCPU_in_aw_bits_lock),
    .auto_in_aw_bits_cache    (auto_fromCPU_in_aw_bits_cache),
    .auto_in_aw_bits_prot     (auto_fromCPU_in_aw_bits_prot),
    .auto_in_aw_bits_qos      (auto_fromCPU_in_aw_bits_qos),
    .auto_in_w_ready          (auto_fromCPU_in_w_ready),
    .auto_in_w_valid          (auto_fromCPU_in_w_valid),
    .auto_in_w_bits_data      (auto_fromCPU_in_w_bits_data),
    .auto_in_w_bits_strb      (auto_fromCPU_in_w_bits_strb),
    .auto_in_w_bits_last      (auto_fromCPU_in_w_bits_last),
    .auto_in_b_ready          (auto_fromCPU_in_b_ready),
    .auto_in_b_valid          (auto_fromCPU_in_b_valid),
    .auto_in_b_bits_id        (auto_fromCPU_in_b_bits_id),
    .auto_in_b_bits_resp      (auto_fromCPU_in_b_bits_resp),
    .auto_in_ar_ready         (auto_fromCPU_in_ar_ready),
    .auto_in_ar_valid         (auto_fromCPU_in_ar_valid),
    .auto_in_ar_bits_id       (auto_fromCPU_in_ar_bits_id),
    .auto_in_ar_bits_addr     (auto_fromCPU_in_ar_bits_addr),
    .auto_in_ar_bits_len      (auto_fromCPU_in_ar_bits_len),
    .auto_in_ar_bits_size     (auto_fromCPU_in_ar_bits_size),
    .auto_in_ar_bits_burst    (auto_fromCPU_in_ar_bits_burst),
    .auto_in_ar_bits_lock     (auto_fromCPU_in_ar_bits_lock),
    .auto_in_ar_bits_cache    (auto_fromCPU_in_ar_bits_cache),
    .auto_in_ar_bits_prot     (auto_fromCPU_in_ar_bits_prot),
    .auto_in_ar_bits_qos      (auto_fromCPU_in_ar_bits_qos),
    .auto_in_r_ready          (auto_fromCPU_in_r_ready),
    .auto_in_r_valid          (auto_fromCPU_in_r_valid),
    .auto_in_r_bits_id        (auto_fromCPU_in_r_bits_id),
    .auto_in_r_bits_data      (auto_fromCPU_in_r_bits_data),
    .auto_in_r_bits_resp      (auto_fromCPU_in_r_bits_resp),
    .auto_in_r_bits_last      (auto_fromCPU_in_r_bits_last),
    .auto_out_1_aw_ready
      (_aplic_ios_1_regmapIn_ready & ~_fromCPU_auto_out_1_ar_valid),
    .auto_out_1_aw_valid      (_fromCPU_auto_out_1_aw_valid),
    .auto_out_1_aw_bits_id    (domainFromCPUIn_1_aw_bits_id),
    .auto_out_1_aw_bits_addr  (domainFromCPUIn_1_aw_bits_addr),
    .auto_out_1_aw_bits_len   (domainFromCPUIn_1_aw_bits_len),
    .auto_out_1_aw_bits_size  (domainFromCPUIn_1_aw_bits_size),
    .auto_out_1_aw_bits_burst (domainFromCPUIn_1_aw_bits_burst),
    .auto_out_1_aw_bits_lock  (domainFromCPUIn_1_aw_bits_lock),
    .auto_out_1_aw_bits_cache (domainFromCPUIn_1_aw_bits_cache),
    .auto_out_1_aw_bits_prot  (domainFromCPUIn_1_aw_bits_prot),
    .auto_out_1_aw_bits_qos   (domainFromCPUIn_1_aw_bits_qos),
    .auto_out_1_w_ready
      (_aplic_ios_1_regmapIn_ready & ~_fromCPU_auto_out_1_ar_valid),
    .auto_out_1_w_valid       (_fromCPU_auto_out_1_w_valid),
    .auto_out_1_w_bits_data   (domainFromCPUIn_1_w_bits_data),
    .auto_out_1_w_bits_strb   (domainFromCPUIn_1_w_bits_strb),
    .auto_out_1_w_bits_last   (domainFromCPUIn_1_w_bits_last),
    .auto_out_1_b_ready       (_fromCPU_auto_out_1_b_ready),
    .auto_out_1_b_valid
      (_aplic_ios_1_regmapOut_valid & ~_aplic_ios_1_regmapOut_bits_read),
    .auto_out_1_b_bits_id     (domainFromCPUIn_1_b_bits_id),
    .auto_out_1_b_bits_resp   (domainFromCPUIn_1_b_bits_resp),
    .auto_out_1_ar_ready      (_aplic_ios_1_regmapIn_ready),
    .auto_out_1_ar_valid      (_fromCPU_auto_out_1_ar_valid),
    .auto_out_1_ar_bits_id    (domainFromCPUIn_1_ar_bits_id),
    .auto_out_1_ar_bits_addr  (domainFromCPUIn_1_ar_bits_addr),
    .auto_out_1_ar_bits_len   (domainFromCPUIn_1_ar_bits_len),
    .auto_out_1_ar_bits_size  (domainFromCPUIn_1_ar_bits_size),
    .auto_out_1_ar_bits_burst (domainFromCPUIn_1_ar_bits_burst),
    .auto_out_1_ar_bits_lock  (domainFromCPUIn_1_ar_bits_lock),
    .auto_out_1_ar_bits_cache (domainFromCPUIn_1_ar_bits_cache),
    .auto_out_1_ar_bits_prot  (domainFromCPUIn_1_ar_bits_prot),
    .auto_out_1_ar_bits_qos   (domainFromCPUIn_1_ar_bits_qos),
    .auto_out_1_r_ready       (_fromCPU_auto_out_1_r_ready),
    .auto_out_1_r_valid
      (_aplic_ios_1_regmapOut_valid & _aplic_ios_1_regmapOut_bits_read),
    .auto_out_1_r_bits_id     (domainFromCPUIn_1_r_bits_id),
    .auto_out_1_r_bits_data   (domainFromCPUIn_1_r_bits_data),
    .auto_out_1_r_bits_resp   (domainFromCPUIn_1_r_bits_resp),
    .auto_out_1_r_bits_last   (domainFromCPUIn_1_r_bits_last),
    .auto_out_0_aw_ready
      (_aplic_ios_0_regmapIn_ready & ~_fromCPU_auto_out_0_ar_valid),
    .auto_out_0_aw_valid      (_fromCPU_auto_out_0_aw_valid),
    .auto_out_0_aw_bits_id    (domainFromCPUIn_aw_bits_id),
    .auto_out_0_aw_bits_addr  (domainFromCPUIn_aw_bits_addr),
    .auto_out_0_aw_bits_len   (domainFromCPUIn_aw_bits_len),
    .auto_out_0_aw_bits_size  (domainFromCPUIn_aw_bits_size),
    .auto_out_0_aw_bits_burst (domainFromCPUIn_aw_bits_burst),
    .auto_out_0_aw_bits_lock  (domainFromCPUIn_aw_bits_lock),
    .auto_out_0_aw_bits_cache (domainFromCPUIn_aw_bits_cache),
    .auto_out_0_aw_bits_prot  (domainFromCPUIn_aw_bits_prot),
    .auto_out_0_aw_bits_qos   (domainFromCPUIn_aw_bits_qos),
    .auto_out_0_w_ready
      (_aplic_ios_0_regmapIn_ready & ~_fromCPU_auto_out_0_ar_valid),
    .auto_out_0_w_valid       (_fromCPU_auto_out_0_w_valid),
    .auto_out_0_w_bits_data   (domainFromCPUIn_w_bits_data),
    .auto_out_0_w_bits_strb   (domainFromCPUIn_w_bits_strb),
    .auto_out_0_w_bits_last   (domainFromCPUIn_w_bits_last),
    .auto_out_0_b_ready       (_fromCPU_auto_out_0_b_ready),
    .auto_out_0_b_valid
      (_aplic_ios_0_regmapOut_valid & ~_aplic_ios_0_regmapOut_bits_read),
    .auto_out_0_b_bits_id     (domainFromCPUIn_b_bits_id),
    .auto_out_0_b_bits_resp   (domainFromCPUIn_b_bits_resp),
    .auto_out_0_ar_ready      (_aplic_ios_0_regmapIn_ready),
    .auto_out_0_ar_valid      (_fromCPU_auto_out_0_ar_valid),
    .auto_out_0_ar_bits_id    (domainFromCPUIn_ar_bits_id),
    .auto_out_0_ar_bits_addr  (domainFromCPUIn_ar_bits_addr),
    .auto_out_0_ar_bits_len   (domainFromCPUIn_ar_bits_len),
    .auto_out_0_ar_bits_size  (domainFromCPUIn_ar_bits_size),
    .auto_out_0_ar_bits_burst (domainFromCPUIn_ar_bits_burst),
    .auto_out_0_ar_bits_lock  (domainFromCPUIn_ar_bits_lock),
    .auto_out_0_ar_bits_cache (domainFromCPUIn_ar_bits_cache),
    .auto_out_0_ar_bits_prot  (domainFromCPUIn_ar_bits_prot),
    .auto_out_0_ar_bits_qos   (domainFromCPUIn_ar_bits_qos),
    .auto_out_0_r_ready       (_fromCPU_auto_out_0_r_ready),
    .auto_out_0_r_valid
      (_aplic_ios_0_regmapOut_valid & _aplic_ios_0_regmapOut_bits_read),
    .auto_out_0_r_bits_id     (domainFromCPUIn_r_bits_id),
    .auto_out_0_r_bits_data   (domainFromCPUIn_r_bits_data),
    .auto_out_0_r_bits_resp   (domainFromCPUIn_r_bits_resp),
    .auto_out_0_r_bits_last   (domainFromCPUIn_r_bits_last)
  );
  AXI4Xbar_7 toIMSIC (
    .clock                  (clock),
    .reset                  (reset),
    .auto_in_1_aw_valid     (_aplic_ios_1_msi_valid),
    .auto_in_1_aw_bits_addr (_aplic_ios_1_msi_bits_addr[31:0]),
    .auto_in_1_w_valid      (_aplic_ios_1_msi_valid),
    .auto_in_1_w_bits_data  (_aplic_ios_1_msi_bits_data),
    .auto_in_1_b_valid      (_toIMSIC_auto_in_1_b_valid),
    .auto_in_0_aw_valid     (_aplic_ios_0_msi_valid),
    .auto_in_0_aw_bits_addr (_aplic_ios_0_msi_bits_addr[31:0]),
    .auto_in_0_w_valid      (_aplic_ios_0_msi_valid),
    .auto_in_0_w_bits_data  (_aplic_ios_0_msi_bits_data),
    .auto_in_0_b_valid      (_toIMSIC_auto_in_0_b_valid),
    .auto_out_aw_valid      (auto_toIMSIC_out_aw_valid),
    .auto_out_aw_bits_id    (auto_toIMSIC_out_aw_bits_id),
    .auto_out_aw_bits_addr  (auto_toIMSIC_out_aw_bits_addr),
    .auto_out_aw_bits_size  (auto_toIMSIC_out_aw_bits_size),
    .auto_out_w_valid       (auto_toIMSIC_out_w_valid),
    .auto_out_w_bits_data   (auto_toIMSIC_out_w_bits_data),
    .auto_out_w_bits_strb   (auto_toIMSIC_out_w_bits_strb),
    .auto_out_w_bits_last   (auto_toIMSIC_out_w_bits_last),
    .auto_out_b_ready       (auto_toIMSIC_out_b_ready),
    .auto_out_b_valid       (auto_toIMSIC_out_b_valid),
    .auto_out_b_bits_id     (auto_toIMSIC_out_b_bits_id),
    .auto_out_r_valid       (auto_toIMSIC_out_r_valid),
    .auto_out_r_bits_id     (auto_toIMSIC_out_r_bits_id)
  );
  APLIC aplic (
    .clock                     (clock),
    .reset                     (reset),
    .ios_0_msi_valid           (_aplic_ios_0_msi_valid),
    .ios_0_msi_bits_addr       (_aplic_ios_0_msi_bits_addr),
    .ios_0_msi_bits_data       (_aplic_ios_0_msi_bits_data),
    .ios_0_ack                 (_toIMSIC_auto_in_0_b_valid),
    .ios_0_regmapIn_ready      (_aplic_ios_0_regmapIn_ready),
    .ios_0_regmapIn_valid
      (_fromCPU_auto_out_0_ar_valid | _fromCPU_auto_out_0_aw_valid
       & _fromCPU_auto_out_0_w_valid),
    .ios_0_regmapIn_bits_read  (_fromCPU_auto_out_0_ar_valid),
    .ios_0_regmapIn_bits_index
      (_fromCPU_auto_out_0_ar_valid
         ? domainFromCPUIn_ar_bits_addr[13:2]
         : domainFromCPUIn_aw_bits_addr[13:2]),
    .ios_0_regmapIn_bits_data  (domainFromCPUIn_w_bits_data),
    .ios_0_regmapIn_bits_mask
      (_fromCPU_auto_out_0_ar_valid
         ? {mask_sub_1_1 | domainFromCPUIn_ar_bits_addr[1]
              & domainFromCPUIn_ar_bits_addr[0],
            mask_sub_1_1 | domainFromCPUIn_ar_bits_addr[1]
              & ~(domainFromCPUIn_ar_bits_addr[0]),
            mask_sub_0_1 | ~(domainFromCPUIn_ar_bits_addr[1])
              & domainFromCPUIn_ar_bits_addr[0],
            mask_sub_0_1 | ~(domainFromCPUIn_ar_bits_addr[1])
              & ~(domainFromCPUIn_ar_bits_addr[0])}
         : domainFromCPUIn_w_bits_strb),
    .ios_0_regmapOut_ready
      (_aplic_ios_0_regmapOut_bits_read
         ? _fromCPU_auto_out_0_r_ready
         : _fromCPU_auto_out_0_b_ready),
    .ios_0_regmapOut_valid     (_aplic_ios_0_regmapOut_valid),
    .ios_0_regmapOut_bits_read (_aplic_ios_0_regmapOut_bits_read),
    .ios_0_regmapOut_bits_data (domainFromCPUIn_r_bits_data),
    .ios_1_msi_valid           (_aplic_ios_1_msi_valid),
    .ios_1_msi_bits_addr       (_aplic_ios_1_msi_bits_addr),
    .ios_1_msi_bits_data       (_aplic_ios_1_msi_bits_data),
    .ios_1_ack                 (_toIMSIC_auto_in_1_b_valid),
    .ios_1_regmapIn_ready      (_aplic_ios_1_regmapIn_ready),
    .ios_1_regmapIn_valid
      (_fromCPU_auto_out_1_ar_valid | _fromCPU_auto_out_1_aw_valid
       & _fromCPU_auto_out_1_w_valid),
    .ios_1_regmapIn_bits_read  (_fromCPU_auto_out_1_ar_valid),
    .ios_1_regmapIn_bits_index
      (_fromCPU_auto_out_1_ar_valid
         ? domainFromCPUIn_1_ar_bits_addr[13:2]
         : domainFromCPUIn_1_aw_bits_addr[13:2]),
    .ios_1_regmapIn_bits_data  (domainFromCPUIn_1_w_bits_data),
    .ios_1_regmapIn_bits_mask
      (_fromCPU_auto_out_1_ar_valid
         ? {mask_sub_1_1_1 | domainFromCPUIn_1_ar_bits_addr[1]
              & domainFromCPUIn_1_ar_bits_addr[0],
            mask_sub_1_1_1 | domainFromCPUIn_1_ar_bits_addr[1]
              & ~(domainFromCPUIn_1_ar_bits_addr[0]),
            mask_sub_0_1_1 | ~(domainFromCPUIn_1_ar_bits_addr[1])
              & domainFromCPUIn_1_ar_bits_addr[0],
            mask_sub_0_1_1 | ~(domainFromCPUIn_1_ar_bits_addr[1])
              & ~(domainFromCPUIn_1_ar_bits_addr[0])}
         : domainFromCPUIn_1_w_bits_strb),
    .ios_1_regmapOut_ready
      (_aplic_ios_1_regmapOut_bits_read
         ? _fromCPU_auto_out_1_r_ready
         : _fromCPU_auto_out_1_b_ready),
    .ios_1_regmapOut_valid     (_aplic_ios_1_regmapOut_valid),
    .ios_1_regmapOut_bits_read (_aplic_ios_1_regmapOut_bits_read),
    .ios_1_regmapOut_bits_data (domainFromCPUIn_1_r_bits_data),
    .intSrcs_1                 (intSrcs_1),
    .intSrcs_2                 (intSrcs_2),
    .intSrcs_3                 (intSrcs_3),
    .intSrcs_4                 (intSrcs_4),
    .intSrcs_5                 (intSrcs_5),
    .intSrcs_6                 (intSrcs_6),
    .intSrcs_7                 (intSrcs_7),
    .intSrcs_8                 (intSrcs_8),
    .intSrcs_9                 (intSrcs_9),
    .intSrcs_10                (intSrcs_10),
    .intSrcs_11                (intSrcs_11),
    .intSrcs_12                (intSrcs_12),
    .intSrcs_13                (intSrcs_13),
    .intSrcs_14                (intSrcs_14),
    .intSrcs_15                (intSrcs_15),
    .intSrcs_16                (intSrcs_16),
    .intSrcs_17                (intSrcs_17),
    .intSrcs_18                (intSrcs_18),
    .intSrcs_19                (intSrcs_19),
    .intSrcs_20                (intSrcs_20),
    .intSrcs_21                (intSrcs_21),
    .intSrcs_22                (intSrcs_22),
    .intSrcs_23                (intSrcs_23),
    .intSrcs_24                (intSrcs_24),
    .intSrcs_25                (intSrcs_25),
    .intSrcs_26                (intSrcs_26),
    .intSrcs_27                (intSrcs_27),
    .intSrcs_28                (intSrcs_28),
    .intSrcs_29                (intSrcs_29),
    .intSrcs_30                (intSrcs_30),
    .intSrcs_31                (intSrcs_31),
    .intSrcs_32                (intSrcs_32),
    .intSrcs_33                (intSrcs_33),
    .intSrcs_34                (intSrcs_34),
    .intSrcs_35                (intSrcs_35),
    .intSrcs_36                (intSrcs_36),
    .intSrcs_37                (intSrcs_37),
    .intSrcs_38                (intSrcs_38),
    .intSrcs_39                (intSrcs_39),
    .intSrcs_40                (intSrcs_40),
    .intSrcs_41                (intSrcs_41),
    .intSrcs_42                (intSrcs_42),
    .intSrcs_43                (intSrcs_43),
    .intSrcs_44                (intSrcs_44),
    .intSrcs_45                (intSrcs_45),
    .intSrcs_46                (intSrcs_46),
    .intSrcs_47                (intSrcs_47),
    .intSrcs_48                (intSrcs_48),
    .intSrcs_49                (intSrcs_49),
    .intSrcs_50                (intSrcs_50),
    .intSrcs_51                (intSrcs_51),
    .intSrcs_52                (intSrcs_52),
    .intSrcs_53                (intSrcs_53),
    .intSrcs_54                (intSrcs_54),
    .intSrcs_55                (intSrcs_55),
    .intSrcs_56                (intSrcs_56),
    .intSrcs_57                (intSrcs_57),
    .intSrcs_58                (intSrcs_58),
    .intSrcs_59                (intSrcs_59),
    .intSrcs_60                (intSrcs_60),
    .intSrcs_61                (intSrcs_61),
    .intSrcs_62                (intSrcs_62),
    .intSrcs_63                (intSrcs_63),
    .intSrcs_64                (intSrcs_64),
    .intSrcs_65                (intSrcs_65),
    .intSrcs_66                (intSrcs_66),
    .intSrcs_67                (intSrcs_67),
    .intSrcs_68                (intSrcs_68),
    .intSrcs_69                (intSrcs_69),
    .intSrcs_70                (intSrcs_70),
    .intSrcs_71                (intSrcs_71),
    .intSrcs_72                (intSrcs_72),
    .intSrcs_73                (intSrcs_73),
    .intSrcs_74                (intSrcs_74),
    .intSrcs_75                (intSrcs_75),
    .intSrcs_76                (intSrcs_76),
    .intSrcs_77                (intSrcs_77),
    .intSrcs_78                (intSrcs_78),
    .intSrcs_79                (intSrcs_79),
    .intSrcs_80                (intSrcs_80),
    .intSrcs_81                (intSrcs_81),
    .intSrcs_82                (intSrcs_82),
    .intSrcs_83                (intSrcs_83),
    .intSrcs_84                (intSrcs_84),
    .intSrcs_85                (intSrcs_85),
    .intSrcs_86                (intSrcs_86),
    .intSrcs_87                (intSrcs_87),
    .intSrcs_88                (intSrcs_88),
    .intSrcs_89                (intSrcs_89),
    .intSrcs_90                (intSrcs_90),
    .intSrcs_91                (intSrcs_91),
    .intSrcs_92                (intSrcs_92),
    .intSrcs_93                (intSrcs_93),
    .intSrcs_94                (intSrcs_94),
    .intSrcs_95                (intSrcs_95),
    .intSrcs_96                (intSrcs_96),
    .intSrcs_97                (intSrcs_97),
    .intSrcs_98                (intSrcs_98),
    .intSrcs_99                (intSrcs_99),
    .intSrcs_100               (intSrcs_100),
    .intSrcs_101               (intSrcs_101),
    .intSrcs_102               (intSrcs_102),
    .intSrcs_103               (intSrcs_103),
    .intSrcs_104               (intSrcs_104),
    .intSrcs_105               (intSrcs_105),
    .intSrcs_106               (intSrcs_106),
    .intSrcs_107               (intSrcs_107),
    .intSrcs_108               (intSrcs_108),
    .intSrcs_109               (intSrcs_109),
    .intSrcs_110               (intSrcs_110),
    .intSrcs_111               (intSrcs_111),
    .intSrcs_112               (intSrcs_112),
    .intSrcs_113               (intSrcs_113),
    .intSrcs_114               (intSrcs_114),
    .intSrcs_115               (intSrcs_115),
    .intSrcs_116               (intSrcs_116),
    .intSrcs_117               (intSrcs_117),
    .intSrcs_118               (intSrcs_118),
    .intSrcs_119               (intSrcs_119),
    .intSrcs_120               (intSrcs_120),
    .intSrcs_121               (intSrcs_121),
    .intSrcs_122               (intSrcs_122),
    .intSrcs_123               (intSrcs_123),
    .intSrcs_124               (intSrcs_124),
    .intSrcs_125               (intSrcs_125),
    .intSrcs_126               (intSrcs_126),
    .intSrcs_127               (intSrcs_127)
  );
endmodule

