// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module IMSICGateWay(
  input        clock,
  input        reset,
  input        msiio_msi_vld_req,
  output       msiio_msi_vld_ack,
  input  [7:0] io_seteipnum,
  input        io_valid_0,
  input        io_valid_1,
  input        io_valid_2,
  input        io_valid_3,
  input        io_valid_4,
  input        io_valid_5,
  output [7:0] msi_data_o,
  output       msi_valid_o_0,
  output       msi_valid_o_1,
  output       msi_valid_o_2,
  output       msi_valid_o_3,
  output       msi_valid_o_4,
  output       msi_valid_o_5
);

  reg        msi_vld_ack_cpu;
  reg  [7:0] msi_data_catch;
  reg  [5:0] msi_intf_valids;
  wire       msi_vld_ris_cpu = msiio_msi_vld_req & ~msi_vld_ack_cpu;
  always @(posedge clock) begin
    msi_vld_ack_cpu <= msiio_msi_vld_req;
    if (reset) begin
      msi_data_catch <= 8'h0;
      msi_intf_valids <= 6'h0;
    end
    else begin
      if (msi_vld_ris_cpu)
        msi_data_catch <= io_seteipnum;
      msi_intf_valids <=
        msi_vld_ris_cpu
          ? {io_valid_5, io_valid_4, io_valid_3, io_valid_2, io_valid_1, io_valid_0}
          : 6'h0;
    end
  end // always @(posedge)
  assign msiio_msi_vld_ack = msi_vld_ack_cpu;
  assign msi_data_o = msi_data_catch;
  assign msi_valid_o_0 = msi_intf_valids[0];
  assign msi_valid_o_1 = msi_intf_valids[1];
  assign msi_valid_o_2 = msi_intf_valids[2];
  assign msi_valid_o_3 = msi_intf_valids[3];
  assign msi_valid_o_4 = msi_intf_valids[4];
  assign msi_valid_o_5 = msi_intf_valids[5];
endmodule

